import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedRectangle66Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedHospitalSoJosWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedDownarrow2Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedImage28Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedImage26Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedImage29Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedImage20Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedRectangle12Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedHospitalFernandoDaFonsecaWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedTabBarWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedSecondiconsmapbloodWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedOurStatusBarWidget6.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedRectangle12Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedFullscreenoneWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedSecondiconsmapbloodWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedSecondiconsmapbloodWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedCitymapfornavigationapptopviewvector212504872Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedImage25Widget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedImage27Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedRectangle59Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedDownarrow3Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedInstitutoPortugusdoSangueedaTransplantaoWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedHospitalSantaMariaWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedRectangle13Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedBloodDonationsfrom9hto18hOpenfromMondaytoSundayAddressW.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedRectangle13Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedDownarrow1Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist1widget/generated/GeneratedDownarrow3Widget1.dart';

/* Frame Blood Donation Centers List 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCentersList1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 132.07757568359375,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 99.26858520507812,
                  height: 74.03080749511719,
                  child: GeneratedRectangle66Widget(),
                ),
                Positioned(
                  left: 19.34886360168457,
                  top: 594.7703247070312,
                  right: null,
                  bottom: null,
                  width: 87.49095916748047,
                  height: 71.50703430175781,
                  child: GeneratedImage28Widget(),
                ),
                Positioned(
                  left: 21.031396865844727,
                  top: 423.9946594238281,
                  right: null,
                  bottom: null,
                  width: 63.935699462890625,
                  height: 66.45948028564453,
                  child: GeneratedImage26Widget(),
                ),
                Positioned(
                  left: 18.507596969604492,
                  top: 331.45611572265625,
                  right: null,
                  bottom: null,
                  width: 66.45948028564453,
                  height: 66.45948028564453,
                  child: GeneratedImage25Widget(),
                ),
                Positioned(
                  left: 0.8411766290664673,
                  top: 322.2023010253906,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle12Widget2(),
                ),
                Positioned(
                  left: 0.8411766290664673,
                  top: 502.23175048828125,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle13Widget(),
                ),
                Positioned(
                  left: 317.1546325683594,
                  top: 531.6758422851562,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow3Widget(),
                ),
                Positioned(
                  left: 0.8411766290664673,
                  top: 412.21697998046875,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle12Widget3(),
                ),
                Positioned(
                  left: 317.9959716796875,
                  top: 441.66107177734375,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow2Widget(),
                ),
                Positioned(
                  left: 95.90347290039062,
                  top: 342.3924865722656,
                  right: null,
                  bottom: null,
                  width: 199.6959228515625,
                  height: 49.11051559448242,
                  child:
                      GeneratedInstitutoPortugusdoSangueedaTransplantaoWidget(),
                ),
                Positioned(
                  left: 91.697265625,
                  top: 429.04217529296875,
                  right: null,
                  bottom: null,
                  width: 204.74346923828125,
                  height: 49.11051559448242,
                  child: GeneratedHospitalFernandoDaFonsecaWidget(),
                ),
                Positioned(
                  left: 317.9959716796875,
                  top: 351.6463623046875,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget(),
                ),
                Positioned(
                  left: 111.88742065429688,
                  top: 521.5806884765625,
                  right: null,
                  bottom: null,
                  width: 160.15675354003906,
                  height: 49.11051559448242,
                  child: GeneratedHospitalSantaMariaWidget(),
                ),
                Positioned(
                  left: 27.761531829833984,
                  top: 531.6758422851562,
                  right: null,
                  bottom: null,
                  width: 74.03080749511719,
                  height: 26.07903480529785,
                  child: GeneratedImage27Widget(),
                ),
                Positioned(
                  left: 0.8411766290664673,
                  top: 592.2463989257812,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle13Widget1(),
                ),
                Positioned(
                  left: 316.3133850097656,
                  top: 621.6904907226562,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow3Widget1(),
                ),
                Positioned(
                  left: 111.04615783691406,
                  top: 611.595458984375,
                  right: null,
                  bottom: null,
                  width: 160.15675354003906,
                  height: 49.11051559448242,
                  child: GeneratedHospitalSoJosWidget(),
                ),
                Positioned(
                  left: -254.90162658691406,
                  top: 172.45816040039062,
                  right: null,
                  bottom: null,
                  width: 15.983924865722656,
                  height: 15.142666816711426,
                  child: GeneratedImage29Widget(),
                ),
                Positioned(
                  left: 77.39579010009766,
                  top: 92.53851318359375,
                  right: null,
                  bottom: null,
                  width: 204.42599487304688,
                  height: 213.21714782714844,
                  child: GeneratedRectangle59Widget(),
                ),
                Positioned(
                  left: 81.60205841064453,
                  top: 96.74481964111328,
                  right: null,
                  bottom: null,
                  width: 196.0133819580078,
                  height: 204.80322265625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504872Widget(),
                ),
                Positioned(
                  left: 145.53773498535156,
                  top: 167.4105987548828,
                  right: null,
                  bottom: null,
                  width: 12.618887901306152,
                  height: 12.618887901306152,
                  child: GeneratedImage20Widget(),
                ),
                Positioned(
                  left: 81.60205841064453,
                  top: 279.2980651855469,
                  right: null,
                  bottom: null,
                  width: 20.190221786499023,
                  height: 20.190221786499023,
                  child: GeneratedFullscreenoneWidget(),
                ),
                Positioned(
                  left: 425.6771545410156,
                  top: -99.26859283447266,
                  right: null,
                  bottom: null,
                  width: 250.1714630126953,
                  height: 95.37977600097656,
                  child:
                      GeneratedBloodDonationsfrom9hto18hOpenfromMondaytoSundayAddressW(),
                ),
                Positioned(
                  left: 169.93421936035156,
                  top: 138.80776977539062,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget(),
                ),
                Positioned(
                  left: 135.44264221191406,
                  top: 213.6798095703125,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget1(),
                ),
                Positioned(
                  left: 229.66368103027344,
                  top: 223.77496337890625,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget2(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget6(),
                ),
                Positioned(
                  left: 0.8411766290664673,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget2(),
                )
              ]),
        ),
      ),
    ));
  }
}
