import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedRightarrow1Widget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedLogo1Widget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedStatusBarWidget28.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedLine15Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedTabBarWidget21.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedLine16Widget1.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedComponent3Widget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedCitymapfornavigationapptopviewvector212504873Widget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedSecondiconsmapbloodWidget13.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedLine17Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedOurStatusBarWidget25.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/Generated28minWidget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedRectangle6Widget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedRectangle8Widget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedLupa1Widget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedLine18Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedRectangle70Widget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/Generated24minWidget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/Generated1h8minWidget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedSecondiconsmapbloodWidget12.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedLine13Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedSecondiconsmapbloodWidget14.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation2widget/generated/GeneratedCarOnWidget9.dart';

/* Frame User and Blood Centers Location 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserandBloodCentersLocation2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 139.64895629882812,
                  top: 708.3402709960938,
                  right: null,
                  bottom: null,
                  width: 83.28466033935547,
                  height: 64.77696990966797,
                  child: GeneratedRectangle70Widget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 87.49095916748047,
                  child: GeneratedRectangle6Widget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 37.856658935546875,
                  child: GeneratedStatusBarWidget28(),
                ),
                Positioned(
                  left: 156.47418212890625,
                  top: 36.174129486083984,
                  right: null,
                  bottom: null,
                  width: 56.3643684387207,
                  height: 39.539188385009766,
                  child: GeneratedLogo1Widget3(),
                ),
                Positioned(
                  left: 64.77694702148438,
                  top: 75.65982818603516,
                  right: null,
                  bottom: null,
                  width: 33.47807312011719,
                  height: 31.914827346801758,
                  child: GeneratedRightarrow1Widget3(),
                ),
                Positioned(
                  left: 310.4244079589844,
                  top: 43.7454719543457,
                  right: null,
                  bottom: null,
                  width: 27.76155662536621,
                  height: 31.967849731445312,
                  child: GeneratedLupa1Widget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 87.49095916748047,
                  child: GeneratedRectangle8Widget3(),
                ),
                Positioned(
                  left: -5.888856410980225,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504873Widget3(),
                ),
                Positioned(
                  left: 111.77864837646484,
                  top: 339.0274658203125,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated1h8minWidget(),
                ),
                Positioned(
                  left: 18.50763702392578,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 42.062957763671875,
                  height: 3.365036725997925,
                  child: GeneratedLine13Widget1(),
                ),
                Positioned(
                  left: 323.55987548828125,
                  top: 476.1527404785156,
                  right: null,
                  bottom: null,
                  width: 24.156780242919922,
                  height: 24.38849639892578,
                  child: GeneratedLine15Widget1(),
                ),
                Positioned(
                  left: 323.67083740234375,
                  top: 475.3800354003906,
                  right: null,
                  bottom: null,
                  width: 3.904461622238159,
                  height: 18.3284969329834,
                  child: GeneratedLine16Widget1(),
                ),
                Positioned(
                  left: 100.10978698730469,
                  top: 282.1649475097656,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated24minWidget(),
                ),
                Positioned(
                  left: 15.983959197998047,
                  top: 386.4810791015625,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated28minWidget(),
                ),
                Positioned(
                  left: 306.21832275390625,
                  top: 503.914306640625,
                  right: null,
                  bottom: null,
                  width: 279.6930236816406,
                  height: 3.365036725997925,
                  child: GeneratedLine17Widget1(),
                ),
                Positioned(
                  left: 18.50763702392578,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 109.71582794189453,
                  height: 3.365036725997925,
                  child: GeneratedLine18Widget1(),
                ),
                Positioned(
                  left: 150.58543395996094,
                  top: 201.90220642089844,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget12(),
                ),
                Positioned(
                  left: 41.22166061401367,
                  top: 428.200927734375,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget13(),
                ),
                Positioned(
                  left: 323.88470458984375,
                  top: 438.2960510253906,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget14(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget25(),
                ),
                Positioned(
                  left: 217.04478454589844,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget9(),
                ),
                Positioned(
                  left: 72.3482666015625,
                  top: 228.822509765625,
                  right: null,
                  bottom: null,
                  width: 95.903564453125,
                  height: 110.2049789428711,
                  child: GeneratedComponent3Widget(),
                ),
                Positioned(
                  left: 0.8412784337997437,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget21(),
                )
              ]),
        ),
      ),
    ));
  }
}
