description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  web3dart: ^2.3.3
  provider: ^4.3.3
  http: ^0.13.0
  web_socket_channel: ^1.2.0
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
    - src/abis/History.json

  fonts: 
    - 
      family: "DM Sans"
      fonts: 
        - 
          asset: "fonts/DMSans-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/DMSans-italic.ttf"
          style: "italic"
          weight: 400
        - 
          asset: "fonts/DMSans-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "Crete Round"
      fonts: 
        - 
          asset: "fonts/CreteRound-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Poppins"
      fonts: 
        - 
          asset: "fonts/Poppins-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/Poppins-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Karla"
      fonts: 
        - 
          asset: "fonts/Karla-regular.ttf"
          style: "normal"
          weight: 400
  uses-material-design: true
