import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/GeneratedFrame11Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/GeneratedFrame15Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/GeneratedFrame14Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/Generated768pxNotifications_alert_badge_mobile2Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/GeneratedChevronWidget27.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/Generated768pxNotifications_alert_badge_mobile1Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/GeneratedFAQsWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/GeneratedBackgroundWidget3.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/GeneratedOurStatusBarWidget17.dart';
import 'package:flutterapp/donate2saveapp/generatedinitialpage2widget/generated/GeneratedTabBarWidget13.dart';

/* Frame Initial Page 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedInitialPage2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 17.666301727294922,
                  top: 53.84068298339844,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget27(),
                ),
                Positioned(
                  left: 7.571221828460693,
                  top: 85.80857849121094,
                  right: null,
                  bottom: null,
                  width: 339.0274963378906,
                  height: 196.0133819580078,
                  child: GeneratedFrame11Widget(),
                ),
                Positioned(
                  left: -0.8413244485855103,
                  top: 331.456298828125,
                  right: null,
                  bottom: null,
                  width: 360.90020751953125,
                  height: 370.9953308105469,
                  child: GeneratedFrame14Widget(),
                ),
                Positioned(
                  left: -0.8413244485855103,
                  top: 331.456298828125,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 0.6752210259437561,
                  child: GeneratedBackgroundWidget3(),
                ),
                Positioned(
                  left: 157.31536865234375,
                  top: 292.7585144042969,
                  right: null,
                  bottom: null,
                  width: 57.1580696105957,
                  height: 33.602813720703125,
                  child: GeneratedFAQsWidget(),
                ),
                Positioned(
                  left: 101.79225158691406,
                  top: -9.2535982131958,
                  right: null,
                  bottom: null,
                  width: 84.12591552734375,
                  height: 84.12591552734375,
                  child: GeneratedFrame15Widget(),
                ),
                Positioned(
                  left: -0.00005763150329585187,
                  top: 702.4515380859375,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget13(),
                ),
                Positioned(
                  left: -0.000007771376658638474,
                  top: 0.0000892130410647951,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget17(),
                ),
                Positioned(
                  left: 324.72589111328125,
                  top: 35.33305740356445,
                  right: null,
                  bottom: null,
                  width: 16.825183868408203,
                  height: 16.825183868408203,
                  child:
                      Generated768pxNotifications_alert_badge_mobile1Widget(),
                ),
                Positioned(
                  left: 299.4882507324219,
                  top: 710.8639526367188,
                  right: null,
                  bottom: null,
                  width: 16.825183868408203,
                  height: 16.825183868408203,
                  child:
                      Generated768pxNotifications_alert_badge_mobile2Widget(),
                )
              ]),
        ),
      ),
    ));
  }
}
