import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedBlood2Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedChevronWidget17.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedBlood4Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDownarrow1Widget13.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedTabBarWidget8.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedPreferredplaceWidget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDonationatHFDF290620211011Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedImage25Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDonationatIPST060520191657Widget1.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedBlood3Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedBlood5Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedRectangle15Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDownarrow1Widget10.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedBlood1Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedOurStatusBarWidget12.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDonationatHFDF210120191907Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDonationatIPST190320181229Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedEdit2Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedRectangle18Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedHistoryWidget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedRectangle16Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDownarrow1Widget9.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDownarrow1Widget11.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDownarrow1Widget12.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedRectangle17Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedDonationatIPST120220201732Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedRectangle19Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedRectangle14Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen5widget/generated/GeneratedLifessaved2BloodsdestinationSeixalWidget.dart';

/* Frame History Screen 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryScreen5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 20.190174102783203,
                  top: 651.1347045898438,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle19Widget1(),
                ),
                Positioned(
                  left: 38.69786071777344,
                  top: 675.5314331054688,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood5Widget1(),
                ),
                Positioned(
                  left: 306.21832275390625,
                  top: 680.5787963867188,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget9(),
                ),
                Positioned(
                  left: 20.190174102783203,
                  top: 208.6323699951172,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle14Widget6(),
                ),
                Positioned(
                  left: 100.95117950439453,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST190320181229Widget2(),
                ),
                Positioned(
                  left: 38.69786071777344,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood1Widget3(),
                ),
                Positioned(
                  left: 20.190174102783203,
                  top: 495.5016784667969,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle17Widget3(),
                ),
                Positioned(
                  left: 20.190174102783203,
                  top: 495.5016784667969,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle18Widget1(),
                ),
                Positioned(
                  left: 38.69786071777344,
                  top: 519.8983154296875,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood4Widget1(),
                ),
                Positioned(
                  left: 20.190174102783203,
                  top: 400.4394836425781,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle16Widget3(),
                ),
                Positioned(
                  left: 38.69786071777344,
                  top: 424.83599853515625,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood3Widget1(),
                ),
                Positioned(
                  left: 20.190174102783203,
                  top: 304.5357971191406,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle15Widget3(),
                ),
                Positioned(
                  left: 38.69786071777344,
                  top: 328.93243408203125,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood2Widget1(),
                ),
                Positioned(
                  left: 100.95117950439453,
                  top: 323.88482666015625,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatHFDF210120191907Widget(),
                ),
                Positioned(
                  left: 100.95117950439453,
                  top: 416.4234313964844,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST060520191657Widget1(),
                ),
                Positioned(
                  left: 100.95117950439453,
                  top: 513.1681518554688,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST120220201732Widget1(),
                ),
                Positioned(
                  left: 109.36360168457031,
                  top: 90.85610961914062,
                  right: null,
                  bottom: null,
                  width: 150.53785705566406,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget5(),
                ),
                Positioned(
                  left: 21.031442642211914,
                  top: 154.79177856445312,
                  right: null,
                  bottom: null,
                  width: 158.47421264648438,
                  height: 49.11051559448242,
                  child: GeneratedPreferredplaceWidget3(),
                ),
                Positioned(
                  left: 177.5057373046875,
                  top: 149.74417114257812,
                  right: null,
                  bottom: null,
                  width: 50.47555160522461,
                  height: 57.20562744140625,
                  child: GeneratedImage25Widget6(),
                ),
                Positioned(
                  left: 302.8533935546875,
                  top: 163.20433044433594,
                  right: null,
                  bottom: null,
                  width: 33.650367736816406,
                  height: 30.28533363342285,
                  child: GeneratedEdit2Widget3(),
                ),
                Positioned(
                  left: 304.5357971191406,
                  top: 238.0763397216797,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget10(),
                ),
                Positioned(
                  left: 306.21832275390625,
                  top: 333.98004150390625,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget11(),
                ),
                Positioned(
                  left: 304.5357971191406,
                  top: 429.0423278808594,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget12(),
                ),
                Positioned(
                  left: 335.6625671386719,
                  top: 552.7074584960938,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget13(),
                ),
                Positioned(
                  left: 17.66643524169922,
                  top: 53.84067153930664,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget17(),
                ),
                Positioned(
                  left: 83.28469848632812,
                  top: 592.2466430664062,
                  right: null,
                  bottom: null,
                  width: 195.4896240234375,
                  height: 49.11051559448242,
                  child: GeneratedLifessaved2BloodsdestinationSeixalWidget(),
                ),
                Positioned(
                  left: 100.95117950439453,
                  top: 669.642333984375,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatHFDF290620211011Widget1(),
                ),
                Positioned(
                  left: 0.00001487829922552919,
                  top: 702.4514770507812,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget8(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget12(),
                )
              ]),
        ),
      ),
    ));
  }
}
