import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedLogo1Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedComponent9Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedOurStatusBarWidget19.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedLupa1Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedRectangle8Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedMapsbuttonWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedLine15Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedStatusBarWidget19.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedCitymapfornavigationapptopviewvector212504873Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedLine12Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedLine16Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedAddressAvdoBrasil531749005LisbonWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedRectangle62Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedIPSTWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedTabBarWidget15.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedSecondiconsmapbloodWidget6.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedArrivaltime1hour8minutesWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedCarOnWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedOpeningHoursMonSun9h18hWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedRectangle6Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails6widget/generated/GeneratedRightarrow1Widget.dart';

/* Frame Blood Donation Center Details 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCenterDetails6Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 0.000049846454203361645,
                  top: -0.000007040212040010374,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 87.49095916748047,
                  child: GeneratedRectangle6Widget(),
                ),
                Positioned(
                  left: 0.000049846454203361645,
                  top: -0.000007040212040010374,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 37.856658935546875,
                  child: GeneratedStatusBarWidget19(),
                ),
                Positioned(
                  left: 156.47421264648438,
                  top: 36.174129486083984,
                  right: null,
                  bottom: null,
                  width: 56.3643684387207,
                  height: 39.539188385009766,
                  child: GeneratedLogo1Widget(),
                ),
                Positioned(
                  left: 64.77710723876953,
                  top: 75.65982818603516,
                  right: null,
                  bottom: null,
                  width: 33.47807312011719,
                  height: 31.914827346801758,
                  child: GeneratedRightarrow1Widget(),
                ),
                Positioned(
                  left: 310.4248352050781,
                  top: 43.7454719543457,
                  right: null,
                  bottom: null,
                  width: 27.76155662536621,
                  height: 31.967849731445312,
                  child: GeneratedLupa1Widget(),
                ),
                Positioned(
                  left: 0.000049846454203361645,
                  top: -0.000007040212040010374,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 87.49095916748047,
                  child: GeneratedRectangle8Widget(),
                ),
                Positioned(
                  left: -5.888574123382568,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504873Widget(),
                ),
                Positioned(
                  left: 213.67987060546875,
                  top: 234.71131896972656,
                  right: null,
                  bottom: null,
                  width: 139.64903259277344,
                  height: 196.0133819580078,
                  child: GeneratedRectangle62Widget(),
                ),
                Positioned(
                  left: 233.0287628173828,
                  top: 354.170166015625,
                  right: null,
                  bottom: null,
                  width: 101.26858520507812,
                  height: 32.28533363342285,
                  child: GeneratedArrivaltime1hour8minutesWidget(),
                ),
                Positioned(
                  left: 229.6636962890625,
                  top: 275.9330139160156,
                  right: null,
                  bottom: null,
                  width: 108.83992004394531,
                  height: 33.96784973144531,
                  child: GeneratedOpeningHoursMonSun9h18hWidget(),
                ),
                Positioned(
                  left: 222.93380737304688,
                  top: 245.6476593017578,
                  right: null,
                  bottom: null,
                  width: 125.30006408691406,
                  height: 21.825183868408203,
                  child: GeneratedIPSTWidget(),
                ),
                Positioned(
                  left: 229.6636962890625,
                  top: 394.5505676269531,
                  right: null,
                  bottom: null,
                  width: 121.98258209228516,
                  height: 23.55525779724121,
                  child: GeneratedMapsbuttonWidget(),
                ),
                Positioned(
                  left: 222.93380737304688,
                  top: 312.1071472167969,
                  right: null,
                  bottom: null,
                  width: 121.45880889892578,
                  height: 37.332889556884766,
                  child: GeneratedAddressAvdoBrasil531749005LisbonWidget1(),
                ),
                Positioned(
                  left: 87.2720947265625,
                  top: 336.513671875,
                  right: null,
                  bottom: null,
                  width: 11.202109336853027,
                  height: 3.2981698513031006,
                  child: GeneratedLine12Widget(),
                ),
                Positioned(
                  left: 323.56005859375,
                  top: 476.1527404785156,
                  right: null,
                  bottom: null,
                  width: 24.156780242919922,
                  height: 24.38849639892578,
                  child: GeneratedLine15Widget(),
                ),
                Positioned(
                  left: 323.6707458496094,
                  top: 475.3800354003906,
                  right: null,
                  bottom: null,
                  width: 3.904461622238159,
                  height: 18.3284969329834,
                  child: GeneratedLine16Widget(),
                ),
                Positioned(
                  left: 323.8846130371094,
                  top: 438.2960510253906,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget6(),
                ),
                Positioned(
                  left: 0.8413166999816895,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget15(),
                ),
                Positioned(
                  left: 72.34814453125,
                  top: 311.26593017578125,
                  right: null,
                  bottom: null,
                  width: 233.87060546875,
                  height: 192.64837646484375,
                  child: GeneratedComponent9Widget(),
                ),
                Positioned(
                  left: 217.04493713378906,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget(),
                ),
                Positioned(
                  left: 0.000049846454203361645,
                  top: -0.000007040212040010374,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget19(),
                )
              ]),
        ),
      ),
    ));
  }
}
