import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedSecondiconsmapbloodWidget5.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedRectangle59Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedDownarrow2Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedRectangle67Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedHospitalFernandoDaFonsecaWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedInstitutoPortugusdoSangueedaTransplantaoWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedImage20Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedRectangle12Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedDownarrow1Widget1.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedTabBarWidget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedDownarrow3Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedImage29Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedOurStatusBarWidget7.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedSecondiconsmapbloodWidget4.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedOpeninghours9h18hOpeningdaysMonSunWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedSecondiconsmapbloodWidget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedCitymapfornavigationapptopviewvector212504872Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedImage26Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedRectangle13Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedHospitalSantaMariaWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedFullscreenoneWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedAddressAvdoBrasil531749005LisbonWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedImage25Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedImage27Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist2widget/generated/GeneratedRectangle12Widget5.dart';

/* Frame Blood Donation Centers List 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCentersList2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 134.6014862060547,
                  top: 707.4990234375,
                  right: null,
                  bottom: null,
                  width: 85.80844116210938,
                  height: 67.30073547363281,
                  child: GeneratedRectangle67Widget(),
                ),
                Positioned(
                  left: 21.0314998626709,
                  top: 531.6758422851562,
                  right: null,
                  bottom: null,
                  width: 63.935699462890625,
                  height: 66.45948028564453,
                  child: GeneratedImage26Widget1(),
                ),
                Positioned(
                  left: 18.507728576660156,
                  top: 331.45611572265625,
                  right: null,
                  bottom: null,
                  width: 66.45948028564453,
                  height: 66.45948028564453,
                  child: GeneratedImage25Widget1(),
                ),
                Positioned(
                  left: 0.8413392901420593,
                  top: 322.2023010253906,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle12Widget4(),
                ),
                Positioned(
                  left: 0.8413392901420593,
                  top: 609.9129028320312,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle13Widget2(),
                ),
                Positioned(
                  left: 317.15478515625,
                  top: 639.3569946289062,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow3Widget2(),
                ),
                Positioned(
                  left: 0.8413392901420593,
                  top: 519.8982543945312,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle12Widget5(),
                ),
                Positioned(
                  left: 317.99603271484375,
                  top: 549.3423461914062,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow2Widget1(),
                ),
                Positioned(
                  left: 95.90357971191406,
                  top: 342.3924865722656,
                  right: null,
                  bottom: null,
                  width: 199.6959228515625,
                  height: 49.11051559448242,
                  child:
                      GeneratedInstitutoPortugusdoSangueedaTransplantaoWidget1(),
                ),
                Positioned(
                  left: 91.69730377197266,
                  top: 536.723388671875,
                  right: null,
                  bottom: null,
                  width: 204.74346923828125,
                  height: 49.11051559448242,
                  child: GeneratedHospitalFernandoDaFonsecaWidget1(),
                ),
                Positioned(
                  left: 348.2813720703125,
                  top: 378.566650390625,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget1(),
                ),
                Positioned(
                  left: 111.88749694824219,
                  top: 629.2619018554688,
                  right: null,
                  bottom: null,
                  width: 160.15675354003906,
                  height: 49.11051559448242,
                  child: GeneratedHospitalSantaMariaWidget1(),
                ),
                Positioned(
                  left: 27.76160430908203,
                  top: 639.3569946289062,
                  right: null,
                  bottom: null,
                  width: 74.03080749511719,
                  height: 26.07903480529785,
                  child: GeneratedImage27Widget1(),
                ),
                Positioned(
                  left: -254.90158081054688,
                  top: 172.45816040039062,
                  right: null,
                  bottom: null,
                  width: 15.983924865722656,
                  height: 15.142666816711426,
                  child: GeneratedImage29Widget1(),
                ),
                Positioned(
                  left: 56.364402770996094,
                  top: 466.89886474609375,
                  right: null,
                  bottom: null,
                  width: 250.1714630126953,
                  height: 55.8405876159668,
                  child: GeneratedAddressAvdoBrasil531749005LisbonWidget(),
                ),
                Positioned(
                  left: 55.523136138916016,
                  top: 408.85198974609375,
                  right: null,
                  bottom: null,
                  width: 250.1714630126953,
                  height: 60.88814926147461,
                  child: GeneratedOpeninghours9h18hOpeningdaysMonSunWidget(),
                ),
                Positioned(
                  left: 77.39588928222656,
                  top: 92.53851318359375,
                  right: null,
                  bottom: null,
                  width: 204.42599487304688,
                  height: 213.21714782714844,
                  child: GeneratedRectangle59Widget1(),
                ),
                Positioned(
                  left: 81.6021957397461,
                  top: 96.74481964111328,
                  right: null,
                  bottom: null,
                  width: 196.0133819580078,
                  height: 204.80322265625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504872Widget1(),
                ),
                Positioned(
                  left: 145.5378875732422,
                  top: 167.4105987548828,
                  right: null,
                  bottom: null,
                  width: 12.618887901306152,
                  height: 12.618887901306152,
                  child: GeneratedImage20Widget1(),
                ),
                Positioned(
                  left: 81.6021957397461,
                  top: 279.2980651855469,
                  right: null,
                  bottom: null,
                  width: 20.190221786499023,
                  height: 20.190221786499023,
                  child: GeneratedFullscreenoneWidget1(),
                ),
                Positioned(
                  left: 169.93441772460938,
                  top: 138.80776977539062,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget3(),
                ),
                Positioned(
                  left: 135.4427490234375,
                  top: 213.6798095703125,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget4(),
                ),
                Positioned(
                  left: 229.66378784179688,
                  top: 223.77496337890625,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget5(),
                ),
                Positioned(
                  left: 0.8413392901420593,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget3(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget7(),
                )
              ]),
        ),
      ),
    ));
  }
}
