import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedTabBarWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedOurStatusBarWidget5.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedRectangle16Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedMafaldaAntunesWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedHistoryWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/Generated768pxNotifications_alert_badge_mobile3Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedImage24Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedEditprofileWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedSecondiconsgoldmedalWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedBloodtypeAWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedSecondiconsclipboardWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedSecondiconsblooddonationWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedRectangle14Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedSecondiconsdonorcardmenWidget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedElegibilitytodonate19032022Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedLivessaved9Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedRectangle15Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedRectangle12Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/Generated768pxNotifications_alert_badge_mobile3Widget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedRectangle17Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofile2widget/generated/GeneratedChevronWidget6.dart';

/* Frame User Profile 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserProfile2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 15.142661094665527,
                  top: 378.5667419433594,
                  right: null,
                  bottom: null,
                  width: 153.1091766357422,
                  height: 124.50636291503906,
                  child: GeneratedRectangle14Widget1(),
                ),
                Positioned(
                  left: 15.142661094665527,
                  top: 526.6284790039062,
                  right: null,
                  bottom: null,
                  width: 329.77362060546875,
                  height: 68.98326110839844,
                  child: GeneratedRectangle16Widget1(),
                ),
                Positioned(
                  left: 15.142661094665527,
                  top: 610.7542114257812,
                  right: null,
                  bottom: null,
                  width: 329.77362060546875,
                  height: 68.98326110839844,
                  child: GeneratedRectangle17Widget1(),
                ),
                Positioned(
                  left: 191.8070526123047,
                  top: 378.5667419433594,
                  right: null,
                  bottom: null,
                  width: 153.1091766357422,
                  height: 124.50636291503906,
                  child: GeneratedRectangle15Widget1(),
                ),
                Positioned(
                  left: -0.00001996071841858793,
                  top: 76.55464172363281,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 280.9805908203125,
                  child: GeneratedRectangle12Widget1(),
                ),
                Positioned(
                  left: 123.66504669189453,
                  top: 298.6471252441406,
                  right: null,
                  bottom: null,
                  width: 129.87139892578125,
                  height: 49.11051559448242,
                  child: GeneratedBloodtypeAWidget1(),
                ),
                Positioned(
                  left: 106.83988952636719,
                  top: 114.41116333007812,
                  right: null,
                  bottom: null,
                  width: 147.22035217285156,
                  height: 141.33155822753906,
                  child: GeneratedImage24Widget1(),
                ),
                Positioned(
                  left: 98.4272232055664,
                  top: 259.10784912109375,
                  right: null,
                  bottom: null,
                  width: 165.20428466796875,
                  height: 49.11051559448242,
                  child: GeneratedMafaldaAntunesWidget1(),
                ),
                Positioned(
                  left: 49.63417434692383,
                  top: 440.81976318359375,
                  right: null,
                  bottom: null,
                  width: 84.44340515136719,
                  height: 55.8405876159668,
                  child: GeneratedLivessaved9Widget1(),
                ),
                Positioned(
                  left: 204.42593383789062,
                  top: 440.81976318359375,
                  right: null,
                  bottom: null,
                  width: 131.55393981933594,
                  height: 49.11051559448242,
                  child: GeneratedElegibilitytodonate19032022Widget1(),
                ),
                Positioned(
                  left: 135.44259643554688,
                  top: 538.406005859375,
                  right: null,
                  bottom: null,
                  width: 106.3161392211914,
                  height: 49.11051559448242,
                  child: GeneratedEditprofileWidget1(),
                ),
                Positioned(
                  left: 151.42654418945312,
                  top: 621.690673828125,
                  right: null,
                  bottom: null,
                  width: 84.91962432861328,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget1(),
                ),
                Positioned(
                  left: 17.666339874267578,
                  top: 54.681705474853516,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget6(),
                ),
                Positioned(
                  left: 251.53643798828125,
                  top: 392.0270080566406,
                  right: null,
                  bottom: null,
                  width: 42.062957763671875,
                  height: 42.062957763671875,
                  child: GeneratedSecondiconsblooddonationWidget1(),
                ),
                Positioned(
                  left: 74.87199401855469,
                  top: 393.7093200683594,
                  right: null,
                  bottom: null,
                  width: 33.650367736816406,
                  height: 40.38044357299805,
                  child: GeneratedSecondiconsgoldmedalWidget1(),
                ),
                Positioned(
                  left: 40.38029861450195,
                  top: 535.0408935546875,
                  right: null,
                  bottom: null,
                  width: 54.681846618652344,
                  height: 50.47555160522461,
                  child: GeneratedSecondiconsdonorcardmenWidget1(),
                ),
                Positioned(
                  left: 38.69782638549805,
                  top: 669.6423950195312,
                  right: null,
                  bottom: null,
                  width: 50.47555160522461,
                  height: 52.99932861328125,
                  child: GeneratedSecondiconsclipboardWidget1(),
                ),
                Positioned(
                  left: -0.00001996071841858793,
                  top: 702.4515380859375,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget1(),
                ),
                Positioned(
                  left: -0.000024588567612227052,
                  top: 0.0000892130410647951,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget5(),
                ),
                Positioned(
                  left: 299.4881591796875,
                  top: 710.8639526367188,
                  right: null,
                  bottom: null,
                  width: 16.825183868408203,
                  height: 16.825183868408203,
                  child:
                      Generated768pxNotifications_alert_badge_mobile3Widget(),
                ),
                Positioned(
                  left: 324.7259216308594,
                  top: 35.33305740356445,
                  right: null,
                  bottom: null,
                  width: 16.825183868408203,
                  height: 16.825183868408203,
                  child:
                      Generated768pxNotifications_alert_badge_mobile3Widget1(),
                )
              ]),
        ),
      ),
    ));
  }
}
