import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDownarrow1Widget17.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedBlood5Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDownarrow1Widget15.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDonationatIPST190320181229Widget3.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedBlood4Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDownarrow1Widget18.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedImage25Widget7.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedRectangle15Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedRectangle17Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedRectangle19Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedLifessaved4BloodsdestinationLouresWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDonationatHFDF290620211011Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedRectangle16Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDownarrow1Widget14.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedRectangle14Widget7.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDonationatIPST060520191657Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDonationatHFDF210120191907Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedTabBarWidget9.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedBlood3Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedEdit2Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedHistoryWidget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedChevronWidget19.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedPreferredplaceWidget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDonationatIPST120220201732Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedRectangle18Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedDownarrow1Widget16.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedOurStatusBarWidget13.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedBlood2Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen4widget/generated/GeneratedBlood1Widget4.dart';

/* Frame History Screen 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryScreen4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 100.95104217529297,
                  top: 670.4838256835938,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatHFDF290620211011Widget2(),
                ),
                Positioned(
                  left: 20.190221786499023,
                  top: 651.97607421875,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle19Widget2(),
                ),
                Positioned(
                  left: 38.69791030883789,
                  top: 676.3724365234375,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood5Widget2(),
                ),
                Positioned(
                  left: 306.2183837890625,
                  top: 681.4200439453125,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget14(),
                ),
                Positioned(
                  left: 20.190221786499023,
                  top: 208.6323699951172,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle14Widget7(),
                ),
                Positioned(
                  left: 100.95104217529297,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST190320181229Widget3(),
                ),
                Positioned(
                  left: 38.69791030883789,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood1Widget4(),
                ),
                Positioned(
                  left: 20.190221786499023,
                  top: 556.0723876953125,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle17Widget4(),
                ),
                Positioned(
                  left: 20.190221786499023,
                  top: 556.0723876953125,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle18Widget2(),
                ),
                Positioned(
                  left: 38.69791030883789,
                  top: 580.468994140625,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood4Widget2(),
                ),
                Positioned(
                  left: 20.190221786499023,
                  top: 400.4394836425781,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle16Widget4(),
                ),
                Positioned(
                  left: 38.69791030883789,
                  top: 424.83599853515625,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood3Widget2(),
                ),
                Positioned(
                  left: 20.190221786499023,
                  top: 304.5357971191406,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle15Widget4(),
                ),
                Positioned(
                  left: 38.69791030883789,
                  top: 328.93243408203125,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood2Widget2(),
                ),
                Positioned(
                  left: 100.95104217529297,
                  top: 323.88482666015625,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatHFDF210120191907Widget1(),
                ),
                Positioned(
                  left: 100.95104217529297,
                  top: 416.4234313964844,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST060520191657Widget2(),
                ),
                Positioned(
                  left: 100.95104217529297,
                  top: 573.7388916015625,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST120220201732Widget2(),
                ),
                Positioned(
                  left: 109.36365509033203,
                  top: 90.85610961914062,
                  right: null,
                  bottom: null,
                  width: 150.53785705566406,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget6(),
                ),
                Positioned(
                  left: 21.0314884185791,
                  top: 154.79177856445312,
                  right: null,
                  bottom: null,
                  width: 158.47421264648438,
                  height: 49.11051559448242,
                  child: GeneratedPreferredplaceWidget4(),
                ),
                Positioned(
                  left: 177.5057830810547,
                  top: 149.74417114257812,
                  right: null,
                  bottom: null,
                  width: 50.47555160522461,
                  height: 57.20562744140625,
                  child: GeneratedImage25Widget7(),
                ),
                Positioned(
                  left: 302.8534240722656,
                  top: 163.20433044433594,
                  right: null,
                  bottom: null,
                  width: 33.650367736816406,
                  height: 30.28533363342285,
                  child: GeneratedEdit2Widget4(),
                ),
                Positioned(
                  left: 304.5357360839844,
                  top: 238.0763397216797,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget15(),
                ),
                Positioned(
                  left: 306.2183837890625,
                  top: 333.98004150390625,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget16(),
                ),
                Positioned(
                  left: 334.8210754394531,
                  top: 455.9624938964844,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget17(),
                ),
                Positioned(
                  left: 305.3771057128906,
                  top: 586.35791015625,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget18(),
                ),
                Positioned(
                  left: 17.66648292541504,
                  top: 53.84067153930664,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget19(),
                ),
                Positioned(
                  left: 83.28468322753906,
                  top: 497.184326171875,
                  right: null,
                  bottom: null,
                  width: 203.06094360351562,
                  height: 49.11051559448242,
                  child: GeneratedLifessaved4BloodsdestinationLouresWidget(),
                ),
                Positioned(
                  left: 0.0000013882109897167538,
                  top: 702.4514770507812,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget9(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget13(),
                )
              ]),
        ),
      ),
    ));
  }
}
