import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedImage13Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedCitymapfornavigationapptopviewvector212504872Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedCarOnWidget7.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedImage19Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedHospitalSantaMariaWidget4.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedComponent4Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedCitymapfornavigationapptopviewvector212504871Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedLine6Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedLine5Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedArrivaltime8minutesWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedLine4Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/Generated10minWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedOpeningHoursMonFri10h15hWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedCarOnWidget8.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedLine3Widget8.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedRectangle63Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedTabBarWidget20.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedImage17Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedAddressAvProfEgasMonizMBWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedLine3Widget7.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedRectangle71Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedSecondiconsmapbloodWidget11.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedLine3Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedImage18Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/Generated30minWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedMapsbuttonWidget5.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/GeneratedOurStatusBarWidget24.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails1widget/generated/Generated15minWidget2.dart';

/* Frame Blood Donation Center Details 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCenterDetails1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 142.1728057861328,
                  top: 705.8164672851562,
                  right: null,
                  bottom: null,
                  width: 79.91962432861328,
                  height: 70.66577911376953,
                  child: GeneratedRectangle71Widget(),
                ),
                Positioned(
                  left: -5.047554969787598,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504871Widget2(),
                ),
                Positioned(
                  left: 112.61994934082031,
                  top: 339.0274658203125,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated30minWidget2(),
                ),
                Positioned(
                  left: 19.34906005859375,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 42.062957763671875,
                  height: 3.365036725997925,
                  child: GeneratedLine5Widget2(),
                ),
                Positioned(
                  left: 73.18965148925781,
                  top: 311.26593017578125,
                  right: null,
                  bottom: null,
                  width: 27.76155662536621,
                  height: 27.76155662536621,
                  child: GeneratedImage19Widget2(),
                ),
                Positioned(
                  left: 169.0932159423828,
                  top: 228.822509765625,
                  right: null,
                  bottom: null,
                  width: 122.58446502685547,
                  height: 3.365036725997925,
                  child: GeneratedLine4Widget2(),
                ),
                Positioned(
                  left: 334.4140930175781,
                  top: 532.5703735351562,
                  right: null,
                  bottom: null,
                  width: 58.38798141479492,
                  height: 0.6888126134872437,
                  child: GeneratedLine3Widget6(),
                ),
                Positioned(
                  left: 324.51214599609375,
                  top: 475.3800354003906,
                  right: null,
                  bottom: null,
                  width: 3.904461622238159,
                  height: 18.3284969329834,
                  child: GeneratedLine6Widget2(),
                ),
                Positioned(
                  left: 100.95108795166016,
                  top: 282.1649475097656,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated10minWidget2(),
                ),
                Positioned(
                  left: 16.825260162353516,
                  top: 386.4810791015625,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated15minWidget2(),
                ),
                Positioned(
                  left: 217.88607788085938,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget7(),
                ),
                Positioned(
                  left: 154.7916717529297,
                  top: 208.63229370117188,
                  right: null,
                  bottom: null,
                  width: 29.444074630737305,
                  height: 30.18017578125,
                  child: GeneratedImage17Widget2(),
                ),
                Positioned(
                  left: 334.8213195800781,
                  top: 529.1520385742188,
                  right: null,
                  bottom: null,
                  width: 316.9940185546875,
                  height: 3.365036725997925,
                  child: GeneratedLine3Widget7(),
                ),
                Positioned(
                  left: 329.7737121582031,
                  top: 445.8674011230469,
                  right: null,
                  bottom: null,
                  width: 29.444074630737305,
                  height: 30.18017578125,
                  child: GeneratedImage13Widget1(),
                ),
                Positioned(
                  left: 19.34906005859375,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 109.71582794189453,
                  height: 3.365036725997925,
                  child: GeneratedLine3Widget8(),
                ),
                Positioned(
                  left: 43.74555587768555,
                  top: 423.1534118652344,
                  right: null,
                  bottom: null,
                  width: 29.444074630737305,
                  height: 30.954023361206055,
                  child: GeneratedImage18Widget2(),
                ),
                Positioned(
                  left: -5.047554969787598,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504872Widget4(),
                ),
                Positioned(
                  left: 182.55311584472656,
                  top: 111.04621124267578,
                  right: null,
                  bottom: null,
                  width: 139.64903259277344,
                  height: 196.0133819580078,
                  child: GeneratedRectangle63Widget(),
                ),
                Positioned(
                  left: 202.74363708496094,
                  top: 227.13998413085938,
                  right: null,
                  bottom: null,
                  width: 101.26858520507812,
                  height: 32.28533363342285,
                  child: GeneratedArrivaltime8minutesWidget(),
                ),
                Positioned(
                  left: 197.6959228515625,
                  top: 152.26792907714844,
                  right: null,
                  bottom: null,
                  width: 108.83992004394531,
                  height: 33.96784973144531,
                  child: GeneratedOpeningHoursMonFri10h15hWidget1(),
                ),
                Positioned(
                  left: 190.96578979492188,
                  top: 121.98257446289062,
                  right: null,
                  bottom: null,
                  width: 122.30006408691406,
                  height: 18.825183868408203,
                  child: GeneratedHospitalSantaMariaWidget4(),
                ),
                Positioned(
                  left: 197.6959228515625,
                  top: 270.8854675292969,
                  right: null,
                  bottom: null,
                  width: 121.98258209228516,
                  height: 23.55525779724121,
                  child: GeneratedMapsbuttonWidget5(),
                ),
                Positioned(
                  left: 201.0609893798828,
                  top: 188.44207763671875,
                  right: null,
                  bottom: null,
                  width: 102.95110321044922,
                  height: 25.55525779724121,
                  child: GeneratedAddressAvProfEgasMonizMBWidget1(),
                ),
                Positioned(
                  left: 150.58546447753906,
                  top: 201.90220642089844,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget11(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.90020751953125,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget24(),
                ),
                Positioned(
                  left: 217.88607788085938,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget8(),
                ),
                Positioned(
                  left: 73.189697265625,
                  top: 228.822509765625,
                  right: null,
                  bottom: null,
                  width: 95.903564453125,
                  height: 110.2049789428711,
                  child: GeneratedComponent4Widget(),
                ),
                Positioned(
                  left: 0.8413127064704895,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget20(),
                )
              ]),
        ),
      ),
    ));
  }
}
