import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedAddressIC192720276AmadoraWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedFullscreenoneWidget2.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedInstitutoPortugusdoSangueedaTransplantaoWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedSecondiconsmapbloodWidget20.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedOpeninghours10h13hOpeningdaysMonFriWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedCitymapfornavigationapptopviewvector212504872Widget5.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedRectangle68Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedHospitalFernandoDaFonsecaWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedImage27Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedRectangle59Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedDownarrow3Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedBloodDonationsfrom9hto18hOpenfromMondaytoSundayAddressW1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedOurStatusBarWidget27.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedImage29Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedImage20Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedRectangle12Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedTabBarWidget23.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedImage25Widget11.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedImage26Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedDownarrow2Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedRectangle12Widget7.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedHospitalSantaMariaWidget5.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedSecondiconsmapbloodWidget18.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedSecondiconsmapbloodWidget19.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedDownarrow1Widget34.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterslist3widget/generated/GeneratedRectangle13Widget3.dart';

/* Frame Blood Donation Centers List 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCentersList3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 142.1728057861328,
                  top: 704.9751586914062,
                  right: null,
                  bottom: null,
                  width: 86.64970397949219,
                  height: 71.50703430175781,
                  child: GeneratedRectangle68Widget(),
                ),
                Positioned(
                  left: 21.031475067138672,
                  top: 423.9946594238281,
                  right: null,
                  bottom: null,
                  width: 63.935699462890625,
                  height: 66.45948028564453,
                  child: GeneratedImage26Widget3(),
                ),
                Positioned(
                  left: 18.507699966430664,
                  top: 331.45611572265625,
                  right: null,
                  bottom: null,
                  width: 66.45948028564453,
                  height: 66.45948028564453,
                  child: GeneratedImage25Widget11(),
                ),
                Positioned(
                  left: 0.8412562012672424,
                  top: 322.2023010253906,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle12Widget6(),
                ),
                Positioned(
                  left: 0.8412562012672424,
                  top: 611.595458984375,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle13Widget3(),
                ),
                Positioned(
                  left: 315.4721984863281,
                  top: 641.0394897460938,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow3Widget3(),
                ),
                Positioned(
                  left: 0.8412562012672424,
                  top: 412.21697998046875,
                  right: null,
                  bottom: null,
                  width: 359.2176818847656,
                  height: 85.80844116210938,
                  child: GeneratedRectangle12Widget7(),
                ),
                Positioned(
                  left: 348.28131103515625,
                  top: 468.5813903808594,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow2Widget2(),
                ),
                Positioned(
                  left: 95.90355682373047,
                  top: 342.3924865722656,
                  right: null,
                  bottom: null,
                  width: 199.6959228515625,
                  height: 49.11051559448242,
                  child:
                      GeneratedInstitutoPortugusdoSangueedaTransplantaoWidget2(),
                ),
                Positioned(
                  left: 91.69725799560547,
                  top: 429.04217529296875,
                  right: null,
                  bottom: null,
                  width: 204.74346923828125,
                  height: 49.11051559448242,
                  child: GeneratedHospitalFernandoDaFonsecaWidget2(),
                ),
                Positioned(
                  left: 317.9960021972656,
                  top: 351.6463623046875,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget34(),
                ),
                Positioned(
                  left: 110.20494842529297,
                  top: 630.9444580078125,
                  right: null,
                  bottom: null,
                  width: 160.15675354003906,
                  height: 49.11051559448242,
                  child: GeneratedHospitalSantaMariaWidget5(),
                ),
                Positioned(
                  left: 26.07903480529785,
                  top: 641.0394897460938,
                  right: null,
                  bottom: null,
                  width: 74.03080749511719,
                  height: 26.07903480529785,
                  child: GeneratedImage27Widget3(),
                ),
                Positioned(
                  left: -254.9015350341797,
                  top: 172.45816040039062,
                  right: null,
                  bottom: null,
                  width: 15.983924865722656,
                  height: 15.142666816711426,
                  child: GeneratedImage29Widget2(),
                ),
                Positioned(
                  left: 425.6771545410156,
                  top: -99.26859283447266,
                  right: null,
                  bottom: null,
                  width: 250.1714630126953,
                  height: 95.37977600097656,
                  child:
                      GeneratedBloodDonationsfrom9hto18hOpenfromMondaytoSundayAddressW1(),
                ),
                Positioned(
                  left: 55.52310562133789,
                  top: 557.7548217773438,
                  right: null,
                  bottom: null,
                  width: 250.1714630126953,
                  height: 55.8405876159668,
                  child: GeneratedAddressIC192720276AmadoraWidget2(),
                ),
                Positioned(
                  left: 54.68185043334961,
                  top: 499.7079162597656,
                  right: null,
                  bottom: null,
                  width: 250.1714630126953,
                  height: 60.88814926147461,
                  child: GeneratedOpeninghours10h13hOpeningdaysMonFriWidget(),
                ),
                Positioned(
                  left: 78.23709869384766,
                  top: 92.53851318359375,
                  right: null,
                  bottom: null,
                  width: 204.42599487304688,
                  height: 213.21714782714844,
                  child: GeneratedRectangle59Widget2(),
                ),
                Positioned(
                  left: 81.60214233398438,
                  top: 96.74481964111328,
                  right: null,
                  bottom: null,
                  width: 196.0133819580078,
                  height: 204.80322265625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504872Widget5(),
                ),
                Positioned(
                  left: 145.537841796875,
                  top: 167.4105987548828,
                  right: null,
                  bottom: null,
                  width: 12.618887901306152,
                  height: 12.618887901306152,
                  child: GeneratedImage20Widget6(),
                ),
                Positioned(
                  left: 81.60214233398438,
                  top: 279.2980651855469,
                  right: null,
                  bottom: null,
                  width: 20.190221786499023,
                  height: 20.190221786499023,
                  child: GeneratedFullscreenoneWidget2(),
                ),
                Positioned(
                  left: 169.93435668945312,
                  top: 138.80776977539062,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget18(),
                ),
                Positioned(
                  left: 135.44271850585938,
                  top: 213.6798095703125,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget19(),
                ),
                Positioned(
                  left: 229.6637725830078,
                  top: 223.77496337890625,
                  right: null,
                  bottom: null,
                  width: 10.095110893249512,
                  height: 10.095110893249512,
                  child: GeneratedSecondiconsmapbloodWidget20(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget27(),
                ),
                Positioned(
                  left: 0.8412562012672424,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget23(),
                )
              ]),
        ),
      ),
    ));
  }
}
