import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedTabBarWidget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedDonationatIPST190320181229Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedChevronWidget13.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedRectangle14Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedDownarrow1Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedEdit2Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedBlood1Widget1.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedImage25Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedOurStatusBarWidget10.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedPreferredplaceWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen7widget/generated/GeneratedHistoryWidget3.dart';

/* Frame History Screen 7
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryScreen7Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 20.18999671936035,
                  top: 208.6323699951172,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle14Widget3(),
                ),
                Positioned(
                  left: 100.95100402832031,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST190320181229Widget1(),
                ),
                Positioned(
                  left: 38.69774627685547,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood1Widget1(),
                ),
                Positioned(
                  left: 109.3635482788086,
                  top: 90.85610961914062,
                  right: null,
                  bottom: null,
                  width: 150.53785705566406,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget3(),
                ),
                Positioned(
                  left: 21.03126335144043,
                  top: 154.79177856445312,
                  right: null,
                  bottom: null,
                  width: 158.47421264648438,
                  height: 49.11051559448242,
                  child: GeneratedPreferredplaceWidget1(),
                ),
                Positioned(
                  left: 177.50543212890625,
                  top: 149.74417114257812,
                  right: null,
                  bottom: null,
                  width: 50.47555160522461,
                  height: 57.20562744140625,
                  child: GeneratedImage25Widget3(),
                ),
                Positioned(
                  left: 302.85321044921875,
                  top: 163.20433044433594,
                  right: null,
                  bottom: null,
                  width: 33.650367736816406,
                  height: 30.28533363342285,
                  child: GeneratedEdit2Widget1(),
                ),
                Positioned(
                  left: 304.5357360839844,
                  top: 238.0763397216797,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget3(),
                ),
                Positioned(
                  left: 17.666316986083984,
                  top: 53.84067153930664,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget13(),
                ),
                Positioned(
                  left: -0.00004176623770035803,
                  top: 702.4514770507812,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget6(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget10(),
                )
              ]),
        ),
      ),
    ));
  }
}
