import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedBlood1Widget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDonationatHFDF210120191907Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedBlood4Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDownarrow1Widget19.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedTabBarWidget10.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedOurStatusBarWidget14.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDownarrow1Widget23.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedBlood5Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedPreferredplaceWidget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedRectangle15Widget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDownarrow1Widget21.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDonationatIPST120220201732Widget3.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedRectangle14Widget8.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDownarrow1Widget22.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedRectangle19Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedEdit2Widget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedRectangle18Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedImage25Widget8.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedLifessaved3BloodsdestinationSintraWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedChevronWidget21.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedBlood2Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedRectangle17Widget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDonationatIPST060520191657Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDonationatIPST190320181229Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedBlood3Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDonationatHFDF290620211011Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedDownarrow1Widget20.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedHistoryWidget7.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen3widget/generated/GeneratedRectangle16Widget5.dart';

/* Frame History Screen 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryScreen3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 100.95111083984375,
                  top: 669.642333984375,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatHFDF290620211011Widget3(),
                ),
                Positioned(
                  left: 20.190223693847656,
                  top: 651.1347045898438,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle19Widget3(),
                ),
                Positioned(
                  left: 38.69792938232422,
                  top: 675.5314331054688,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood5Widget3(),
                ),
                Positioned(
                  left: 306.2183532714844,
                  top: 680.5787963867188,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget19(),
                ),
                Positioned(
                  left: 20.190223693847656,
                  top: 208.6323699951172,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle14Widget8(),
                ),
                Positioned(
                  left: 100.95111083984375,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST190320181229Widget4(),
                ),
                Positioned(
                  left: 38.69792938232422,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood1Widget5(),
                ),
                Positioned(
                  left: 20.190223693847656,
                  top: 555.2312622070312,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle17Widget5(),
                ),
                Positioned(
                  left: 20.190223693847656,
                  top: 555.2312622070312,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle18Widget3(),
                ),
                Positioned(
                  left: 38.69792938232422,
                  top: 579.6277465820312,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood4Widget3(),
                ),
                Positioned(
                  left: 20.190223693847656,
                  top: 460.1688232421875,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle16Widget5(),
                ),
                Positioned(
                  left: 38.69792938232422,
                  top: 484.5653381347656,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood3Widget3(),
                ),
                Positioned(
                  left: 20.190223693847656,
                  top: 304.5357971191406,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle15Widget5(),
                ),
                Positioned(
                  left: 38.69792938232422,
                  top: 328.93243408203125,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood2Widget3(),
                ),
                Positioned(
                  left: 100.95111083984375,
                  top: 323.88482666015625,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatHFDF210120191907Widget2(),
                ),
                Positioned(
                  left: 100.95111083984375,
                  top: 476.15277099609375,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST060520191657Widget3(),
                ),
                Positioned(
                  left: 100.95111083984375,
                  top: 572.8975830078125,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST120220201732Widget3(),
                ),
                Positioned(
                  left: 109.36370849609375,
                  top: 90.85610961914062,
                  right: null,
                  bottom: null,
                  width: 150.53785705566406,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget7(),
                ),
                Positioned(
                  left: 21.03148651123047,
                  top: 154.79177856445312,
                  right: null,
                  bottom: null,
                  width: 158.47421264648438,
                  height: 49.11051559448242,
                  child: GeneratedPreferredplaceWidget5(),
                ),
                Positioned(
                  left: 177.50570678710938,
                  top: 149.74417114257812,
                  right: null,
                  bottom: null,
                  width: 50.47555160522461,
                  height: 57.20562744140625,
                  child: GeneratedImage25Widget8(),
                ),
                Positioned(
                  left: 302.8533020019531,
                  top: 163.20433044433594,
                  right: null,
                  bottom: null,
                  width: 33.650367736816406,
                  height: 30.28533363342285,
                  child: GeneratedEdit2Widget5(),
                ),
                Positioned(
                  left: 304.53582763671875,
                  top: 238.0763397216797,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget20(),
                ),
                Positioned(
                  left: 336.503662109375,
                  top: 360.90032958984375,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget21(),
                ),
                Positioned(
                  left: 304.53582763671875,
                  top: 488.77166748046875,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget22(),
                ),
                Positioned(
                  left: 305.3770751953125,
                  top: 585.5166015625,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget23(),
                ),
                Positioned(
                  left: 17.666446685791016,
                  top: 53.84067153930664,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget21(),
                ),
                Positioned(
                  left: 83.28466796875,
                  top: 401.28076171875,
                  right: null,
                  bottom: null,
                  width: 195.4896240234375,
                  height: 49.11051559448242,
                  child: GeneratedLifessaved3BloodsdestinationSintraWidget(),
                ),
                Positioned(
                  left: -6.762337534382823e-7,
                  top: 702.4514770507812,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget10(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget14(),
                )
              ]),
        ),
      ),
    ));
  }
}
