import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedAddressAvProfEgasMonizMBWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedArrivaltime24minutesWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedStatusBarWidget23.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedComponent7Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedRightarrow1Widget2.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedSecondiconsmapbloodWidget8.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedTabBarWidget17.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedCarOnWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedLupa1Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedRectangle8Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedLogo1Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedOpeningHoursMonFri10h15hWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedOurStatusBarWidget21.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedMapsbuttonWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedRectangle60Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedHospitalSantaMariaWidget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails4widget/generated/GeneratedCitymapfornavigationapptopviewvector212504873Widget2.dart';

/* Frame Blood Donation Center Details 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCenterDetails4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -0.00001298089227930177,
                  top: -0.000006615262464038096,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 87.49095916748047,
                  child: GeneratedRectangle6Widget2(),
                ),
                Positioned(
                  left: -0.00001298089227930177,
                  top: -0.000006615262464038096,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 37.856658935546875,
                  child: GeneratedStatusBarWidget23(),
                ),
                Positioned(
                  left: 156.47421264648438,
                  top: 36.174129486083984,
                  right: null,
                  bottom: null,
                  width: 56.3643684387207,
                  height: 39.539188385009766,
                  child: GeneratedLogo1Widget2(),
                ),
                Positioned(
                  left: 64.77686309814453,
                  top: 75.65982818603516,
                  right: null,
                  bottom: null,
                  width: 33.47807312011719,
                  height: 31.914827346801758,
                  child: GeneratedRightarrow1Widget2(),
                ),
                Positioned(
                  left: 310.4243469238281,
                  top: 43.7454719543457,
                  right: null,
                  bottom: null,
                  width: 27.76155662536621,
                  height: 31.967849731445312,
                  child: GeneratedLupa1Widget2(),
                ),
                Positioned(
                  left: -0.00001298089227930177,
                  top: -0.000006615262464038096,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 87.49095916748047,
                  child: GeneratedRectangle8Widget2(),
                ),
                Positioned(
                  left: -5.889059543609619,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504873Widget2(),
                ),
                Positioned(
                  left: 183.39476013183594,
                  top: 121.98257446289062,
                  right: null,
                  bottom: null,
                  width: 139.64903259277344,
                  height: 196.0133819580078,
                  child: GeneratedRectangle60Widget(),
                ),
                Positioned(
                  left: 203.5844268798828,
                  top: 238.0763397216797,
                  right: null,
                  bottom: null,
                  width: 101.26858520507812,
                  height: 32.28533363342285,
                  child: GeneratedArrivaltime24minutesWidget(),
                ),
                Positioned(
                  left: 198.53707885742188,
                  top: 163.20428466796875,
                  right: null,
                  bottom: null,
                  width: 108.83992004394531,
                  height: 33.96784973144531,
                  child: GeneratedOpeningHoursMonFri10h15hWidget(),
                ),
                Positioned(
                  left: 191.8071746826172,
                  top: 132.9189453125,
                  right: null,
                  bottom: null,
                  width: 122.30006408691406,
                  height: 18.825183868408203,
                  child: GeneratedHospitalSantaMariaWidget3(),
                ),
                Positioned(
                  left: 198.53707885742188,
                  top: 281.8218078613281,
                  right: null,
                  bottom: null,
                  width: 121.98258209228516,
                  height: 23.55525779724121,
                  child: GeneratedMapsbuttonWidget2(),
                ),
                Positioned(
                  left: 201.9023895263672,
                  top: 199.37844848632812,
                  right: null,
                  bottom: null,
                  width: 102.95110321044922,
                  height: 25.55525779724121,
                  child: GeneratedAddressAvProfEgasMonizMBWidget(),
                ),
                Positioned(
                  left: 150.58560180664062,
                  top: 201.90220642089844,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget8(),
                ),
                Positioned(
                  left: -0.00001298089227930177,
                  top: -0.000006615262464038096,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget21(),
                ),
                Positioned(
                  left: 72.348388671875,
                  top: 228.822509765625,
                  right: null,
                  bottom: null,
                  width: 95.9033203125,
                  height: 110.2049789428711,
                  child: GeneratedComponent7Widget(),
                ),
                Positioned(
                  left: 217.04469299316406,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget2(),
                ),
                Positioned(
                  left: 0.8410749435424805,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget17(),
                )
              ]),
        ),
      ),
    ));
  }
}
