import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen1widget/GeneratedHistoryScreen1Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedTabBarWidget7.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedImage26Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedRectangle20Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedRectangle47Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/Generated2021Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/Generated2019Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedRectangle50Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedImage25Widget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedRectangle51Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedRectangle48Widget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedOurStatusBarWidget11.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/Generated2020Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedYearsWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedChevronWidget15.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedRectangle49Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedBloodCentersWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/Generated2018Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen6widget/generated/GeneratedRectangle47Widget.dart';
import 'package:provider/provider.dart';

import '../../contract_linking.dart';
import 'generated/GeneratedHistoryWidget4.dart';

/* Frame History Screen 6
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryScreen6Widget extends StatefulWidget {
  _GeneratedHistoryScreen6WidgetState createState() => _GeneratedHistoryScreen6WidgetState();
}

class _GeneratedHistoryScreen6WidgetState extends State<GeneratedHistoryScreen6Widget> {
  var donations;
  var result;
  var preferedPlace;

  @override
  Widget build(BuildContext context) {

    var contractLink = Provider.of<ContractLinking>(context);

    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 109.36365509033203,
                  top: 90.85610961914062,
                  right: null,
                  bottom: null,
                  width: 150.53785705566406,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget4(),
                ),
                Positioned(
                  left: 17.666540145874023,
                  top: 53.84067153930664,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget15(),
                ),
                Positioned(
                  left: 23.555408477783203,
                  top: 190.96588134765625,
                  right: null,
                  bottom: null,
                  width: 317.1546936035156,
                  height: 259.1078796386719,
                  child: GeneratedRectangle20Widget(),
                ),
                Positioned(
                  left: 37.01543426513672,
                  top: 209.4735107421875,
                  right: null,
                  bottom: null,
                  width: 292.7582092285156,
                  height: 95.90354919433594,
                  child: GeneratedRectangle50Widget(),
                ),
                Positioned(
                  left: 36.17416763305664,
                  top: 336.5038146972656,
                  right: null,
                  bottom: null,
                  width: 292.7582092285156,
                  height: 95.90354919433594,
                  child: GeneratedRectangle51Widget(),
                ),
                Positioned(
                  left: 52.15811538696289,
                  top: 250.69534301757812,
                  right: null,
                  bottom: null,
                  width: 64.77696990966797,
                  height: 37.015403747558594,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByYear, [BigInt.from(2018)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: GeneratedRectangle47Widget(),
                  ),
                ),
                Positioned(
                  left: 117.77631378173828,
                  top: 250.69534301757812,
                  right: null,
                  bottom: null,
                  width: 64.77696990966797,
                  height: 37.015403747558594,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByYear, [BigInt.from(2019)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: GeneratedRectangle47Widget1(),
                  ),
                ),
                Positioned(
                  left: 183.39451599121094,
                  top: 250.69534301757812,
                  right: null,
                  bottom: null,
                  width: 64.77696990966797,
                  height: 37.015403747558594,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByYear, [BigInt.from(2020)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: GeneratedRectangle48Widget(),
                  ),
                ),
                Positioned(
                  left: 157.31561279296875,
                  top: 214.5211181640625,
                  right: null,
                  bottom: null,
                  width: 55.47555160522461,
                  height: 31.07903480529785,
                  child: GeneratedYearsWidget(),
                ),
                Positioned(
                  left: 64.77687072753906,
                  top: 251.53660583496094,
                  right: null,
                  bottom: null,
                  width: 57.1580696105957,
                  height: 41.17414474487305,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByYear, [BigInt.from(2018)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                    child: Generated2018Widget(),
                  ),
                ),
                Positioned(
                  left: 131.23646545410156,
                  top: 251.53660583496094,
                  right: null,
                  bottom: null,
                  width: 57.1580696105957,
                  height: 41.17414474487305,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByYear, [BigInt.from(2019)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: Generated2019Widget(),
                  ),
                ),
                Positioned(
                  left: 196.01339721679688,
                  top: 251.53660583496094,
                  right: null,
                  bottom: null,
                  width: 57.1580696105957,
                  height: 41.17414474487305,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByYear, [BigInt.from(2020)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: Generated2020Widget(),
                  ),
                ),
                Positioned(
                  left: 111.04618072509766,
                  top: 347.440185546875,
                  right: null,
                  bottom: null,
                  width: 144.17283630371094,
                  height: 28.9202938079834,
                  child: GeneratedBloodCentersWidget(),
                ),
                Positioned(
                  left: 104.31616973876953,
                  top: 378.5668029785156,
                  right: null,
                  bottom: null,
                  width: 42.90422058105469,
                  height: 45.42799758911133,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByLocation, [BigInt.from(0)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: GeneratedImage25Widget5(),
                  ),
                ),
                Positioned(
                  left: 204.4260711669922,
                  top: 378.5668029785156,
                  right: null,
                  bottom: null,
                  width: 48.793033599853516,
                  height: 44.58674240112305,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByLocation, [BigInt.from(1)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: GeneratedImage26Widget2(),
                  ),
                ),
                Positioned(
                  left: 249.01284790039062,
                  top: 250.69534301757812,
                  right: null,
                  bottom: null,
                  width: 64.77696990966797,
                  height: 37.015403747558594,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByYear, [BigInt.from(2021)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: GeneratedRectangle49Widget(),
                  ),
                ),
                Positioned(
                  left: 260.79034423828125,
                  top: 250.69534301757812,
                  right: null,
                  bottom: null,
                  width: 57.1580696105957,
                  height: 41.17414474487305,
                  child: GestureDetector(
                    onTap: () async{
                      result = await contractLink.readContract(contractLink.getBloodDonationsByYear, [BigInt.from(2019)]);
                      donations = result[0];
                      debugPrint(donations.toString());

                      result = await contractLink.readContract(contractLink.getpreferedPlace, []);
                      preferedPlace = result[0];
                      debugPrint(preferedPlace.toString());

                      Navigator.push(context, MaterialPageRoute(
                          builder: (context) => GeneratedHistoryScreen1Widget(bloodDonations: donations, preferedPlace: preferedPlace))
                      );
                    },
                  child: Generated2021Widget(),
                  ),
                ),
                Positioned(
                  left: 0.00005895975846215151,
                  top: 702.4514770507812,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget7(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget11(),
                )
              ]),
        ),
      ),
    ));
  }
}
