import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedintro2widget/generated/GeneratedOurStatusBarWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedintro2widget/generated/GeneratedCupertino_activity_indicator1Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedintro2widget/generated/GeneratedRectangle41Widget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;

/* Frame Intro 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntro2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedInitialPageWidget'),
      child: Container(
        decoration: BoxDecoration(
          boxShadow: kIsWeb
              ? []
              : [
                  BoxShadow(
                    color: Color.fromARGB(63, 0, 0, 0),
                    offset: Offset(0.0, 3.365036725997925),
                    blurRadius: 3.365036725997925,
                  )
                ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(33.650367736816406),
          child: Container(
            width: 360.0589294433594,
            height: 779.0060424804688,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(33.650367736816406),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(33.650367736816406),
                    child: Container(
                      color: Color.fromARGB(255, 246, 247, 248),
                    ),
                  ),
                  Positioned(
                    left: -10.095297813415527,
                    top: 68.14198303222656,
                    right: null,
                    bottom: null,
                    width: 360.4079284667969,
                    height: 710.8640747070312,
                    child: GeneratedRectangle41Widget(),
                  ),
                  Positioned(
                    left: -0.00004213069405523129,
                    top: -0.000005426470124803018,
                    right: null,
                    bottom: null,
                    width: 360.0589294433594,
                    height: 76.5545883178711,
                    child: GeneratedOurStatusBarWidget(),
                  ),
                  Positioned(
                    left: 158.15660095214844,
                    top: 368.47149658203125,
                    right: null,
                    bottom: null,
                    width: 42.062957763671875,
                    height: 42.062957763671875,
                    child: GeneratedCupertino_activity_indicator1Widget(),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
