import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedLine3Widget9.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedLine3Widget10.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedSecondiconsmapbloodWidget17.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedLine5Widget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/Generated19minWidget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedSecondiconsmapbloodWidget15.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedLine10Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedCitymapfornavigationapptopviewvector212504871Widget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedOurStatusBarWidget26.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedRectangle69Widget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedComponent2Widget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedSecondiconsmapbloodWidget16.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/Generated8minWidget.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedTabBarWidget22.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/Generated10minWidget3.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedCarOnWidget10.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedLine9Widget1.dart';
import 'package:flutterapp/donate2saveapp/generateduserandbloodcenterslocation1widget/generated/GeneratedCarOnWidget11.dart';

/* Frame User and Blood Centers Location 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedUserandBloodCentersLocation1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: 145.5378875732422,
                  top: 707.4990234375,
                  right: null,
                  bottom: null,
                  width: 82.44340515136719,
                  height: 66.45948028564453,
                  child: GeneratedRectangle69Widget(),
                ),
                Positioned(
                  left: -5.047569274902344,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504871Widget3(),
                ),
                Positioned(
                  left: 217.8861541748047,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget10(),
                ),
                Positioned(
                  left: 41.2216796875,
                  top: 428.200927734375,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget15(),
                ),
                Positioned(
                  left: 323.8847351074219,
                  top: 438.2960510253906,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget16(),
                ),
                Positioned(
                  left: 150.58535766601562,
                  top: 201.90220642089844,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget17(),
                ),
                Positioned(
                  left: 19.348955154418945,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 42.062957763671875,
                  height: 3.365036725997925,
                  child: GeneratedLine5Widget3(),
                ),
                Positioned(
                  left: 334.8210754394531,
                  top: 529.1520385742188,
                  right: null,
                  bottom: null,
                  width: 316.9940185546875,
                  height: 3.365036725997925,
                  child: GeneratedLine3Widget9(),
                ),
                Positioned(
                  left: 19.348955154418945,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 109.71582794189453,
                  height: 3.365036725997925,
                  child: GeneratedLine3Widget10(),
                ),
                Positioned(
                  left: 334.41412353515625,
                  top: 532.5703735351562,
                  right: null,
                  bottom: null,
                  width: 58.38798141479492,
                  height: 0.6888126134872437,
                  child: GeneratedLine9Widget1(),
                ),
                Positioned(
                  left: 324.51214599609375,
                  top: 475.3800354003906,
                  right: null,
                  bottom: null,
                  width: 3.904461622238159,
                  height: 18.3284969329834,
                  child: GeneratedLine10Widget1(),
                ),
                Positioned(
                  left: 14.301384925842285,
                  top: 389.0048828125,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated10minWidget3(),
                ),
                Positioned(
                  left: 98.42730712890625,
                  top: 284.6887512207031,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated8minWidget(),
                ),
                Positioned(
                  left: 115.14364624023438,
                  top: 340.7099914550781,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated19minWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.90020751953125,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget26(),
                ),
                Positioned(
                  left: 73.18951416015625,
                  top: 228.822509765625,
                  right: null,
                  bottom: null,
                  width: 95.90353393554688,
                  height: 110.2049789428711,
                  child: GeneratedComponent2Widget(),
                ),
                Positioned(
                  left: 217.8861541748047,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget11(),
                ),
                Positioned(
                  left: 0.8412682414054871,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget22(),
                )
              ]),
        ),
      ),
    ));
  }
}
