import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedLifessaved2BloodsdestinationCascaisWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedOurStatusBarWidget9.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedTabBarWidget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedDonationatIPST190320181229Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedImage25Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedBlood1Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedRectangle14Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedHistoryWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedChevronWidget11.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedDownarrow1Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedEdit2Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen8widget/generated/GeneratedPreferredplaceWidget.dart';

/* Frame History Screen 8
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryScreen8Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 20.189807891845703,
                  top: 208.6323699951172,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle14Widget2(),
                ),
                Positioned(
                  left: 100.95069122314453,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST190320181229Widget(),
                ),
                Positioned(
                  left: 38.69743347167969,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood1Widget(),
                ),
                Positioned(
                  left: 109.36335754394531,
                  top: 90.85610961914062,
                  right: null,
                  bottom: null,
                  width: 150.53785705566406,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget2(),
                ),
                Positioned(
                  left: 21.031076431274414,
                  top: 154.79177856445312,
                  right: null,
                  bottom: null,
                  width: 158.47421264648438,
                  height: 49.11051559448242,
                  child: GeneratedPreferredplaceWidget(),
                ),
                Positioned(
                  left: 177.5052490234375,
                  top: 149.74417114257812,
                  right: null,
                  bottom: null,
                  width: 50.47555160522461,
                  height: 57.20562744140625,
                  child: GeneratedImage25Widget2(),
                ),
                Positioned(
                  left: 302.85302734375,
                  top: 163.20433044433594,
                  right: null,
                  bottom: null,
                  width: 33.650367736816406,
                  height: 30.28533363342285,
                  child: GeneratedEdit2Widget(),
                ),
                Positioned(
                  left: 334.8209228515625,
                  top: 264.99664306640625,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget2(),
                ),
                Positioned(
                  left: 17.66625213623047,
                  top: 53.84067153930664,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget11(),
                ),
                Positioned(
                  left: 77.39546203613281,
                  top: 305.377197265625,
                  right: null,
                  bottom: null,
                  width: 213.997314453125,
                  height: 49.11051559448242,
                  child: GeneratedLifessaved2BloodsdestinationCascaisWidget(),
                ),
                Positioned(
                  left: -0.00010733037197496742,
                  top: 702.4514770507812,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget5(),
                ),
                Positioned(
                  left: -0.00010733037197496742,
                  top: 0.000023115324438549578,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget9(),
                )
              ]),
        ),
      ),
    ));
  }
}
