import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedBlood2Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDownarrow1Widget28.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDonationatIPST190320181229Widget5.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedHistoryWidget8.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedRectangle16Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedBlood1Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDownarrow1Widget27.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedImage25Widget9.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDonationatIPST120220201732Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDownarrow1Widget24.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedBlood5Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedBlood3Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedRectangle15Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedChevronWidget23.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedOurStatusBarWidget15.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedRectangle14Widget9.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedEdit2Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedRectangle18Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedBlood4Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedTabBarWidget11.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedLifessaved2BloodsdestinationCascaisWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDownarrow1Widget25.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDownarrow1Widget26.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDonationatHFDF210120191907Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDonationatHFDF290620211011Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedRectangle17Widget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedPreferredplaceWidget6.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedRectangle19Widget4.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen2widget/generated/GeneratedDonationatIPST060520191657Widget4.dart';

/* Frame History Screen 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryScreen2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 100.951171875,
                  top: 669.642333984375,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatHFDF290620211011Widget4(),
                ),
                Positioned(
                  left: 20.19028663635254,
                  top: 651.1347045898438,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle19Widget4(),
                ),
                Positioned(
                  left: 38.697975158691406,
                  top: 675.5314331054688,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood5Widget4(),
                ),
                Positioned(
                  left: 306.2183532714844,
                  top: 680.5787963867188,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget24(),
                ),
                Positioned(
                  left: 20.19028663635254,
                  top: 208.6323699951172,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle14Widget9(),
                ),
                Positioned(
                  left: 100.951171875,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST190320181229Widget5(),
                ),
                Positioned(
                  left: 38.697975158691406,
                  top: 233.0288543701172,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood1Widget6(),
                ),
                Positioned(
                  left: 20.19028663635254,
                  top: 555.2312622070312,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle17Widget6(),
                ),
                Positioned(
                  left: 20.19028663635254,
                  top: 555.2312622070312,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle18Widget4(),
                ),
                Positioned(
                  left: 38.697975158691406,
                  top: 579.6277465820312,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood4Widget4(),
                ),
                Positioned(
                  left: 20.19028663635254,
                  top: 460.1688232421875,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle16Widget6(),
                ),
                Positioned(
                  left: 38.697975158691406,
                  top: 484.5653381347656,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood3Widget4(),
                ),
                Positioned(
                  left: 20.19028663635254,
                  top: 364.2652587890625,
                  right: null,
                  bottom: null,
                  width: 318.8371887207031,
                  height: 84.9671859741211,
                  child: GeneratedRectangle15Widget6(),
                ),
                Positioned(
                  left: 38.697975158691406,
                  top: 388.6618957519531,
                  right: null,
                  bottom: null,
                  width: 40.38044357299805,
                  height: 36.17414474487305,
                  child: GeneratedBlood2Widget4(),
                ),
                Positioned(
                  left: 100.951171875,
                  top: 383.6142883300781,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatHFDF210120191907Widget3(),
                ),
                Positioned(
                  left: 100.951171875,
                  top: 476.15277099609375,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST060520191657Widget4(),
                ),
                Positioned(
                  left: 100.951171875,
                  top: 572.8975830078125,
                  right: null,
                  bottom: null,
                  width: 205.58474731445312,
                  height: 49.11051559448242,
                  child: GeneratedDonationatIPST120220201732Widget4(),
                ),
                Positioned(
                  left: 109.3637466430664,
                  top: 90.85610961914062,
                  right: null,
                  bottom: null,
                  width: 150.53785705566406,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget8(),
                ),
                Positioned(
                  left: 21.031553268432617,
                  top: 154.79177856445312,
                  right: null,
                  bottom: null,
                  width: 158.47421264648438,
                  height: 49.11051559448242,
                  child: GeneratedPreferredplaceWidget6(),
                ),
                Positioned(
                  left: 177.50572204589844,
                  top: 149.74417114257812,
                  right: null,
                  bottom: null,
                  width: 50.47555160522461,
                  height: 57.20562744140625,
                  child: GeneratedImage25Widget9(),
                ),
                Positioned(
                  left: 302.8533935546875,
                  top: 163.20433044433594,
                  right: null,
                  bottom: null,
                  width: 33.650367736816406,
                  height: 30.28533363342285,
                  child: GeneratedEdit2Widget6(),
                ),
                Positioned(
                  left: 334.82122802734375,
                  top: 264.99664306640625,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget25(),
                ),
                Positioned(
                  left: 306.2183532714844,
                  top: 393.7093505859375,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget26(),
                ),
                Positioned(
                  left: 304.535888671875,
                  top: 488.77166748046875,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget27(),
                ),
                Positioned(
                  left: 305.3771057128906,
                  top: 585.5166015625,
                  right: null,
                  bottom: null,
                  width: 30.28533363342285,
                  height: 26.9202938079834,
                  child: GeneratedDownarrow1Widget28(),
                ),
                Positioned(
                  left: 17.666486740112305,
                  top: 53.84067153930664,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget23(),
                ),
                Positioned(
                  left: 77.39588165283203,
                  top: 305.377197265625,
                  right: null,
                  bottom: null,
                  width: 213.997314453125,
                  height: 49.11051559448242,
                  child: GeneratedLifessaved2BloodsdestinationCascaisWidget1(),
                ),
                Positioned(
                  left: 0.000004925611847284017,
                  top: 702.4514770507812,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget11(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget15(),
                )
              ]),
        ),
      ),
    ));
  }
}
