import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedImage18Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedRectangle65Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedMapsbuttonWidget4.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedLine5Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedCarOnWidget5.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedHospitalFernandodaFonsecaWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedImage17Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedTabBarWidget19.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedOurStatusBarWidget23.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedOpeningHoursMonFri10h13hWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedImage19Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedSecondiconsmapbloodWidget10.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedCarOnWidget6.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/Generated15minWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedLine6Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedComponent5Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedAddressIC192720276AmadoraWidget1.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedCitymapfornavigationapptopviewvector212504871Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/Generated30minWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedLine3Widget5.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedLine4Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedImage13Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/Generated10minWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedCitymapfornavigationapptopviewvector212504872Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedArrivaltime10minutesWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedLine3Widget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails2widget/generated/GeneratedLine3Widget4.dart';

/* Frame Blood Donation Center Details 2
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCenterDetails2Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -5.047585487365723,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504871Widget1(),
                ),
                Positioned(
                  left: 112.61979675292969,
                  top: 339.0274658203125,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated30minWidget1(),
                ),
                Positioned(
                  left: 19.348909378051758,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 42.062957763671875,
                  height: 3.365036725997925,
                  child: GeneratedLine5Widget1(),
                ),
                Positioned(
                  left: 73.18949890136719,
                  top: 311.26593017578125,
                  right: null,
                  bottom: null,
                  width: 27.76155662536621,
                  height: 27.76155662536621,
                  child: GeneratedImage19Widget1(),
                ),
                Positioned(
                  left: 169.0930633544922,
                  top: 228.822509765625,
                  right: null,
                  bottom: null,
                  width: 122.58446502685547,
                  height: 3.365036725997925,
                  child: GeneratedLine4Widget1(),
                ),
                Positioned(
                  left: 334.4139404296875,
                  top: 532.5703735351562,
                  right: null,
                  bottom: null,
                  width: 58.38798141479492,
                  height: 0.6888126134872437,
                  child: GeneratedLine3Widget3(),
                ),
                Positioned(
                  left: 324.5121154785156,
                  top: 475.3800354003906,
                  right: null,
                  bottom: null,
                  width: 3.904461622238159,
                  height: 18.3284969329834,
                  child: GeneratedLine6Widget1(),
                ),
                Positioned(
                  left: 100.95093536376953,
                  top: 282.1649475097656,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated10minWidget1(),
                ),
                Positioned(
                  left: 16.82510757446289,
                  top: 386.4810791015625,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated15minWidget1(),
                ),
                Positioned(
                  left: 217.88604736328125,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget5(),
                ),
                Positioned(
                  left: 154.79176330566406,
                  top: 208.63229370117188,
                  right: null,
                  bottom: null,
                  width: 29.444074630737305,
                  height: 30.18017578125,
                  child: GeneratedImage17Widget1(),
                ),
                Positioned(
                  left: 334.8211669921875,
                  top: 529.1520385742188,
                  right: null,
                  bottom: null,
                  width: 316.9940185546875,
                  height: 3.365036725997925,
                  child: GeneratedLine3Widget4(),
                ),
                Positioned(
                  left: 329.7735595703125,
                  top: 445.8674011230469,
                  right: null,
                  bottom: null,
                  width: 29.444074630737305,
                  height: 30.18017578125,
                  child: GeneratedImage13Widget(),
                ),
                Positioned(
                  left: 19.348909378051758,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 109.71582794189453,
                  height: 3.365036725997925,
                  child: GeneratedLine3Widget5(),
                ),
                Positioned(
                  left: 43.74540328979492,
                  top: 423.1534118652344,
                  right: null,
                  bottom: null,
                  width: 29.444074630737305,
                  height: 30.954023361206055,
                  child: GeneratedImage18Widget1(),
                ),
                Positioned(
                  left: -5.047585487365723,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504872Widget3(),
                ),
                Positioned(
                  left: 73.18949890136719,
                  top: 389.5030212402344,
                  right: null,
                  bottom: null,
                  width: 139.64903259277344,
                  height: 196.0133819580078,
                  child: GeneratedRectangle65Widget(),
                ),
                Positioned(
                  left: 96.7447280883789,
                  top: 505.5967712402344,
                  right: null,
                  bottom: null,
                  width: 101.26858520507812,
                  height: 32.28533363342285,
                  child: GeneratedArrivaltime10minutesWidget(),
                ),
                Positioned(
                  left: 89.17344665527344,
                  top: 430.7247009277344,
                  right: null,
                  bottom: null,
                  width: 108.83992004394531,
                  height: 33.96784973144531,
                  child: GeneratedOpeningHoursMonFri10h13hWidget1(),
                ),
                Positioned(
                  left: 82.44331359863281,
                  top: 398.7568664550781,
                  right: null,
                  bottom: null,
                  width: 122.30006408691406,
                  height: 18.825183868408203,
                  child: GeneratedHospitalFernandodaFonsecaWidget1(),
                ),
                Positioned(
                  left: 90.8561019897461,
                  top: 549.3423461914062,
                  right: null,
                  bottom: null,
                  width: 121.98258209228516,
                  height: 23.55525779724121,
                  child: GeneratedMapsbuttonWidget4(),
                ),
                Positioned(
                  left: 83.28457641601562,
                  top: 466.89886474609375,
                  right: null,
                  bottom: null,
                  width: 121.45880889892578,
                  height: 25.55525779724121,
                  child: GeneratedAddressIC192720276AmadoraWidget1(),
                ),
                Positioned(
                  left: 41.22160339355469,
                  top: 428.200927734375,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget10(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.90020751953125,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget23(),
                ),
                Positioned(
                  left: 217.88604736328125,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget6(),
                ),
                Positioned(
                  left: 19.348876953125,
                  top: 311.26593017578125,
                  right: null,
                  bottom: null,
                  width: 81.60213470458984,
                  height: 134.60145568847656,
                  child: GeneratedComponent5Widget(),
                ),
                Positioned(
                  left: 0.8411605954170227,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget19(),
                )
              ]),
        ),
      ),
    ));
  }
}
