import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedintro4widget/generated/GeneratedRectangle41Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedintro4widget/generated/GeneratedOurStatusBarWidget3.dart';
import 'package:flutterapp/donate2saveapp/generatedintro4widget/generated/GeneratedCupertino_activity_indicator1Widget1.dart';

/* Frame Intro 4
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntro4Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedInitialPage2Widget'),
      child: Container(
        decoration: BoxDecoration(
          boxShadow: kIsWeb
              ? []
              : [
                  BoxShadow(
                    color: Color.fromARGB(63, 0, 0, 0),
                    offset: Offset(0.0, 3.365036725997925),
                    blurRadius: 3.365036725997925,
                  )
                ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(33.650367736816406),
          child: Container(
            width: 360.0589294433594,
            height: 779.0060424804688,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(33.650367736816406),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(33.650367736816406),
                    child: Container(
                      color: Color.fromARGB(255, 246, 247, 248),
                    ),
                  ),
                  Positioned(
                    left: -10.09488296508789,
                    top: 68.14197540283203,
                    right: null,
                    bottom: null,
                    width: 379.4079284667969,
                    height: 710.8640747070312,
                    child: GeneratedRectangle41Widget1(),
                  ),
                  Positioned(
                    left: -0.000018459040802554227,
                    top: 0.0000341094309987966,
                    right: null,
                    bottom: null,
                    width: 360.0589294433594,
                    height: 76.5545883178711,
                    child: GeneratedOurStatusBarWidget3(),
                  ),
                  Positioned(
                    left: 158.15701293945312,
                    top: 368.4715576171875,
                    right: null,
                    bottom: null,
                    width: 42.062957763671875,
                    height: 42.062957763671875,
                    child: GeneratedCupertino_activity_indicator1Widget1(),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
