import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedBackgroundWidget.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedBackgroundWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedLogo2Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedBackgroundWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedNotificationsWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedGroupWidget20.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedImage27Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/Generated2dWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/Generated11minWidget.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedGroupWidget21.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedTabBarWidget4.dart';
import 'package:flutterapp/donate2saveapp/generatednotificationswidget/generated/GeneratedOurStatusBarWidget8.dart';
import 'package:provider/provider.dart';

import '../../contract_linking.dart';

/* Frame Notifications
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedNotificationsWidget extends StatefulWidget {
  final notifications;

  GeneratedNotificationsWidget({Key key, this.notifications}) : super(key: key);

  _GeneratedNotificationsWidgetState createState() => _GeneratedNotificationsWidgetState();
}

class _GeneratedNotificationsWidgetState extends State<GeneratedNotificationsWidget> {
  var notifications;
  var result;


  @override
  void initState() {
    Future.delayed(Duration(milliseconds: 300)).then((value) async{
      var contract = Provider.of<ContractLinking>(context, listen: false);
      result = await contract.readContract(contract.getNotifications, []);
      notifications = result[0];
      debugPrint("here"+notifications.toString());
    });
    super.initState();
  }


  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              clipBehavior: Clip.none,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 246, 247, 248),
                  ),
                ),
                Positioned(
                  left: 30.80767822265625,
                  top: 150.140869140625,
                  right: null,
                  bottom: null,
                  child: Container(
                    width: 300.77362060546875,
                    height: 490.98326110839844,
                    child: Padding(
                      padding: EdgeInsets.fromLTRB(0.0, 3.0, 0.0, 3.0),
                      child: SingleChildScrollView(
                        child: Column(
                          children: widget.notifications.map<Widget>((notification) => GeneratedGroupWidget20(notification: notification)).toList(),
                        ),
                      ),
                    )
                  ),
                ),
                Positioned(
                  left: 93.37969970703125,
                  top: 92.53871154785156,
                  right: null,
                  bottom: null,
                  width: 179.1406707763672,
                  height: 52.11051559448242,
                  child: GeneratedNotificationsWidget1(),
                ),
                Positioned(
                  left: -0.0000018171263036492746,
                  top: 702.4515380859375,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget4(),
                ),
                Positioned(
                  left: -0.000026482388420845382,
                  top: 0.0000892130410647951,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget8(),
                )
              ]),
        ),
      ),
    ));
  }
}
