import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedOpeningHoursMonFri10h13hWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedAddressIC192720276AmadoraWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedRectangle61Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedTabBarWidget16.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedComponent8Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedMapsbuttonWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedOurStatusBarWidget20.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedCitymapfornavigationapptopviewvector212504873Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedHospitalFernandodaFonsecaWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedArrivaltime28minutesWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedSecondiconsmapbloodWidget7.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedRightarrow1Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedLogo1Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedCarOnWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedRectangle8Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedStatusBarWidget21.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails5widget/generated/GeneratedLupa1Widget1.dart';

/* Frame Blood Donation Center Details 5
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCenterDetails5Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -0.00004172934131929651,
                  top: -0.000007040212040010374,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 87.49095916748047,
                  child: GeneratedRectangle6Widget1(),
                ),
                Positioned(
                  left: -0.00004172934131929651,
                  top: -0.000007040212040010374,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 37.856658935546875,
                  child: GeneratedStatusBarWidget21(),
                ),
                Positioned(
                  left: 156.474609375,
                  top: 36.174129486083984,
                  right: null,
                  bottom: null,
                  width: 56.3643684387207,
                  height: 39.539188385009766,
                  child: GeneratedLogo1Widget1(),
                ),
                Positioned(
                  left: 64.77725982666016,
                  top: 75.65982818603516,
                  right: null,
                  bottom: null,
                  width: 33.47807312011719,
                  height: 31.914827346801758,
                  child: GeneratedRightarrow1Widget1(),
                ),
                Positioned(
                  left: 310.42498779296875,
                  top: 43.7454719543457,
                  right: null,
                  bottom: null,
                  width: 27.76155662536621,
                  height: 31.967849731445312,
                  child: GeneratedLupa1Widget1(),
                ),
                Positioned(
                  left: -0.00004172934131929651,
                  top: -0.000007040212040010374,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 87.49095916748047,
                  child: GeneratedRectangle8Widget1(),
                ),
                Positioned(
                  left: -5.888422012329102,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504873Widget1(),
                ),
                Positioned(
                  left: 77.3962631225586,
                  top: 370.1540832519531,
                  right: null,
                  bottom: null,
                  width: 139.64903259277344,
                  height: 196.0133819580078,
                  child: GeneratedRectangle61Widget(),
                ),
                Positioned(
                  left: 100.95149230957031,
                  top: 486.247802734375,
                  right: null,
                  bottom: null,
                  width: 101.26858520507812,
                  height: 32.28533363342285,
                  child: GeneratedArrivaltime28minutesWidget(),
                ),
                Positioned(
                  left: 93.38033294677734,
                  top: 411.3757629394531,
                  right: null,
                  bottom: null,
                  width: 108.83992004394531,
                  height: 33.96784973144531,
                  child: GeneratedOpeningHoursMonFri10h13hWidget(),
                ),
                Positioned(
                  left: 86.65044403076172,
                  top: 379.4079284667969,
                  right: null,
                  bottom: null,
                  width: 122.30006408691406,
                  height: 18.825183868408203,
                  child: GeneratedHospitalFernandodaFonsecaWidget(),
                ),
                Positioned(
                  left: 95.0626220703125,
                  top: 529.9932861328125,
                  right: null,
                  bottom: null,
                  width: 121.98258209228516,
                  height: 23.55525779724121,
                  child: GeneratedMapsbuttonWidget1(),
                ),
                Positioned(
                  left: 87.49121856689453,
                  top: 447.5499267578125,
                  right: null,
                  bottom: null,
                  width: 121.45880889892578,
                  height: 25.55525779724121,
                  child: GeneratedAddressIC192720276AmadoraWidget(),
                ),
                Positioned(
                  left: 41.2217903137207,
                  top: 428.200927734375,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget7(),
                ),
                Positioned(
                  left: -0.00004172934131929651,
                  top: -0.000007040212040010374,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget20(),
                ),
                Positioned(
                  left: 18.508056640625,
                  top: 311.26593017578125,
                  right: null,
                  bottom: null,
                  width: 81.60213470458984,
                  height: 134.60145568847656,
                  child: GeneratedComponent8Widget(),
                ),
                Positioned(
                  left: 217.0453338623047,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget1(),
                ),
                Positioned(
                  left: 0.8417127728462219,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget16(),
                )
              ]),
        ),
      ),
    ));
  }
}
