import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedintro1widget/generated/GeneratedComponent1Widget.dart';

/* Frame Intro 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIntro1Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIntro2Widget'),
      child: Container(
        decoration: BoxDecoration(
          boxShadow: kIsWeb
              ? []
              : [
                  BoxShadow(
                    color: Color.fromARGB(63, 0, 0, 0),
                    offset: Offset(0.0, 3.368481159210205),
                    blurRadius: 3.368481159210205,
                  )
                ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.circular(33.684814453125),
          child: Container(
            width: 360.4275207519531,
            height: 780.6456298828125,
            decoration: BoxDecoration(
              borderRadius: BorderRadius.circular(33.684814453125),
            ),
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.circular(33.684814453125),
                    child: Container(
                      color: Color.fromARGB(255, 246, 247, 248),
                    ),
                  ),
                  Positioned(
                    left: 0.0,
                    top: -0.000006749362910341006,
                    right: null,
                    bottom: null,
                    width: 360.4275207519531,
                    height: 780.6456298828125,
                    child: GeneratedComponent1Widget(),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
