
import 'dart:convert';

import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen1widget/generated/GeneratedPreferredplaceWidget7.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen1widget/generated/GeneratedHistoryWidget9.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen1widget/generated/GeneratedTabBarWidget12.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen1widget/generated/GeneratedOurStatusBarWidget16.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen1widget/generated/GeneratedEdit2Widget7.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen1widget/generated/GeneratedChevronWidget25.dart';
import 'package:flutterapp/donate2saveapp/generatedhistoryscreen1widget/generated/GeneratedImage25Widget10.dart';
import 'package:flutterapp/donate2saveapp/generateduserprofilewidget/generated/GeneratedBloodDonationWidget.dart';

/* Frame History Screen 1
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedHistoryScreen1Widget extends StatefulWidget {
  final bloodDonations;
  final preferedPlace;

  GeneratedHistoryScreen1Widget({Key key, this.bloodDonations, this.preferedPlace}) : super(key: key);

  _GeneratedHistoryScreen1WidgetState createState() => _GeneratedHistoryScreen1WidgetState();
}

class _GeneratedHistoryScreen1WidgetState extends State<GeneratedHistoryScreen1Widget> {



  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
          decoration: BoxDecoration(
            boxShadow: kIsWeb
                ? []
                : [
                    BoxShadow(
                      color: Color.fromARGB(63, 0, 0, 0),
                      offset: Offset(0.0, 3.365036725997925),
                      blurRadius: 3.365036725997925,
                    )
                  ],
          ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            width: 360.0589294433594,
            height: 779.0060424804688,
            child: Stack(
                clipBehavior: Clip.none,
                fit: StackFit.expand,
                alignment: Alignment.center,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      color: Color.fromARGB(255, 246, 247, 248),
                    ),
                  ),
            Positioned(
                left: 30,
                top: 210.85610961914062,
                right: null,
                bottom: null,
                child: Container(
                    width: 300.77362060546875,
                    height: 490.98326110839844,
                    child: Padding(
                      padding: EdgeInsets.fromLTRB(0.0, 3.0, 0.0, 3.0),
                      child: SingleChildScrollView(
                        child: Column(
                          children: widget.bloodDonations.map<Widget>((donation) => GeneratedBloodDonationWidget(donation: donation)).toList(),
                        ),
                      ),
                    ))),
                Positioned(
                  left: 109.36365509033203,
                  top: 90.85610961914062,
                  right: null,
                  bottom: null,
                  width: 150.53785705566406,
                  height: 52.11051559448242,
                  child: GeneratedHistoryWidget9(),
                ),
                Positioned(
                  left: 21.031490325927734,
                  top: 154.79177856445312,
                  right: null,
                  bottom: null,
                  width: 158.47421264648438,
                  height: 49.11051559448242,
                  child: GeneratedPreferredplaceWidget7(),
                ),
                Positioned(
                  left: 177.5056610107422,
                  top: 149.74417114257812,
                  right: null,
                  bottom: null,
                  width: 50.47555160522461,
                  height: 57.20562744140625,
                  child: GeneratedImage25Widget10(preferedPlace: widget.preferedPlace),
                ),
                Positioned(
                  left: 302.85333251953125,
                  top: 163.20433044433594,
                  right: null,
                  bottom: null,
                  width: 33.650367736816406,
                  height: 30.28533363342285,
                  child: GeneratedEdit2Widget7(),
                ),
                Positioned(
                  left: 17.666362762451172,
                  top: 53.84067153930664,
                  right: null,
                  bottom: null,
                  width: 5.888814449310303,
                  height: 10.936369895935059,
                  child: GeneratedChevronWidget25(),
                ),
                Positioned(
                  left: 0.0000027026298994314857,
                  top: 702.4514770507812,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget12(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget16(),
                )
              ]),
        ),
      ),
    ));
  }
}
