import 'package:flutter/material.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedLine12Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedLine3Widget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedLine3Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedCitymapfornavigationapptopviewvector212504872Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedAddressAvdoBrasil531749005LisbonWidget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedComponent6Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/Generated30minWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedMapsbuttonWidget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedImage17Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedLine6Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedImage19Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedCitymapfornavigationapptopviewvector212504871Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/Generated10minWidget.dart';
import 'package:flutter/foundation.dart' show kIsWeb;
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedSecondiconsmapbloodWidget9.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedOurStatusBarWidget22.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/Generated15minWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedLine5Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedTabBarWidget18.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedOpeningHoursMonSun9h18hWidget1.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedLine4Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedImage18Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedArrivaltime19minutesWidget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedCarOnWidget4.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedRectangle64Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedLine3Widget2.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedLine10Widget.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedCarOnWidget3.dart';
import 'package:flutterapp/donate2saveapp/generatedblooddonationcenterdetails3widget/generated/GeneratedIPSTWidget1.dart';

/* Frame Blood Donation Center Details 3
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedBloodDonationCenterDetails3Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: kIsWeb
            ? []
            : [
                BoxShadow(
                  color: Color.fromARGB(63, 0, 0, 0),
                  offset: Offset(0.0, 3.365036725997925),
                  blurRadius: 3.365036725997925,
                )
              ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 360.0589294433594,
          height: 779.0060424804688,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 255, 255, 255),
                  ),
                ),
                Positioned(
                  left: -5.047698974609375,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504871Widget(),
                ),
                Positioned(
                  left: 112.61992645263672,
                  top: 339.0274658203125,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated30minWidget(),
                ),
                Positioned(
                  left: 19.34879493713379,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 42.062957763671875,
                  height: 3.365036725997925,
                  child: GeneratedLine5Widget(),
                ),
                Positioned(
                  left: 73.18938446044922,
                  top: 311.26593017578125,
                  right: null,
                  bottom: null,
                  width: 27.76155662536621,
                  height: 27.76155662536621,
                  child: GeneratedImage19Widget(),
                ),
                Positioned(
                  left: 334.4139404296875,
                  top: 532.5703735351562,
                  right: null,
                  bottom: null,
                  width: 58.38798141479492,
                  height: 0.6888126134872437,
                  child: GeneratedLine3Widget(),
                ),
                Positioned(
                  left: 324.5121154785156,
                  top: 475.3800354003906,
                  right: null,
                  bottom: null,
                  width: 3.904461622238159,
                  height: 18.3284969329834,
                  child: GeneratedLine6Widget(),
                ),
                Positioned(
                  left: 100.95094299316406,
                  top: 282.1649475097656,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated10minWidget(),
                ),
                Positioned(
                  left: 16.824995040893555,
                  top: 386.4810791015625,
                  right: null,
                  bottom: null,
                  width: 36.49163055419922,
                  height: 23.031478881835938,
                  child: Generated15minWidget(),
                ),
                Positioned(
                  left: 217.8860626220703,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget3(),
                ),
                Positioned(
                  left: 154.79153442382812,
                  top: 208.63229370117188,
                  right: null,
                  bottom: null,
                  width: 29.444074630737305,
                  height: 30.18017578125,
                  child: GeneratedImage17Widget(),
                ),
                Positioned(
                  left: 334.8211669921875,
                  top: 529.1520385742188,
                  right: null,
                  bottom: null,
                  width: 316.9940185546875,
                  height: 3.365036725997925,
                  child: GeneratedLine3Widget1(),
                ),
                Positioned(
                  left: 19.34879493713379,
                  top: 420.6296081542969,
                  right: null,
                  bottom: null,
                  width: 109.71582794189453,
                  height: 3.365036725997925,
                  child: GeneratedLine3Widget2(),
                ),
                Positioned(
                  left: 43.74528884887695,
                  top: 423.1534118652344,
                  right: null,
                  bottom: null,
                  width: 29.444074630737305,
                  height: 30.954023361206055,
                  child: GeneratedImage18Widget(),
                ),
                Positioned(
                  left: -5.047698974609375,
                  top: 76.5545883178711,
                  right: null,
                  bottom: null,
                  width: 372.6778564453125,
                  height: 625.0556640625,
                  child:
                      GeneratedCitymapfornavigationapptopviewvector212504872Widget2(),
                ),
                Positioned(
                  left: 213.67971801757812,
                  top: 237.23509216308594,
                  right: null,
                  bottom: null,
                  width: 139.64903259277344,
                  height: 196.0133819580078,
                  child: GeneratedRectangle64Widget(),
                ),
                Positioned(
                  left: 233.02862548828125,
                  top: 356.69390869140625,
                  right: null,
                  bottom: null,
                  width: 101.26858520507812,
                  height: 32.28533363342285,
                  child: GeneratedArrivaltime19minutesWidget(),
                ),
                Positioned(
                  left: 229.66378784179688,
                  top: 278.4568176269531,
                  right: null,
                  bottom: null,
                  width: 108.83992004394531,
                  height: 33.96784973144531,
                  child: GeneratedOpeningHoursMonSun9h18hWidget1(),
                ),
                Positioned(
                  left: 222.93341064453125,
                  top: 248.17147827148438,
                  right: null,
                  bottom: null,
                  width: 125.30006408691406,
                  height: 21.825183868408203,
                  child: GeneratedIPSTWidget1(),
                ),
                Positioned(
                  left: 229.66378784179688,
                  top: 397.0743408203125,
                  right: null,
                  bottom: null,
                  width: 121.98258209228516,
                  height: 23.55525779724121,
                  child: GeneratedMapsbuttonWidget3(),
                ),
                Positioned(
                  left: 222.93341064453125,
                  top: 314.6309509277344,
                  right: null,
                  bottom: null,
                  width: 121.45880889892578,
                  height: 37.332889556884766,
                  child: GeneratedAddressAvdoBrasil531749005LisbonWidget2(),
                ),
                Positioned(
                  left: 87.2714614868164,
                  top: 335.67236328125,
                  right: null,
                  bottom: null,
                  width: 11.202109336853027,
                  height: 3.2981698513031006,
                  child: GeneratedLine12Widget1(),
                ),
                Positioned(
                  left: 324.5121154785156,
                  top: 475.3800354003906,
                  right: null,
                  bottom: null,
                  width: 3.904461622238159,
                  height: 18.3284969329834,
                  child: GeneratedLine10Widget(),
                ),
                Positioned(
                  left: 323.88446044921875,
                  top: 438.2960510253906,
                  right: null,
                  bottom: null,
                  width: 36.17414474487305,
                  height: 35.332889556884766,
                  child: GeneratedSecondiconsmapbloodWidget9(),
                ),
                Positioned(
                  left: -0.0000673274407745339,
                  top: 0.000001017579847939487,
                  right: null,
                  bottom: null,
                  width: 360.90020751953125,
                  height: 76.5545883178711,
                  child: GeneratedOurStatusBarWidget22(),
                ),
                Positioned(
                  left: 169.09307861328125,
                  top: 228.822509765625,
                  right: null,
                  bottom: null,
                  width: 122.58446502685547,
                  height: 3.365036725997925,
                  child: GeneratedLine4Widget(),
                ),
                Positioned(
                  left: 73.189453125,
                  top: 311.26593017578125,
                  right: null,
                  bottom: null,
                  width: 261.6318359375,
                  height: 221.4151153564453,
                  child: GeneratedComponent6Widget(),
                ),
                Positioned(
                  left: 217.8860626220703,
                  top: 627.579345703125,
                  right: null,
                  bottom: null,
                  width: 127.87139892578125,
                  height: 52.1580696105957,
                  child: GeneratedCarOnWidget4(),
                ),
                Positioned(
                  left: 0.8411688804626465,
                  top: 702.4513549804688,
                  right: null,
                  bottom: null,
                  width: 360.0589294433594,
                  height: 76.5545883178711,
                  child: GeneratedTabBarWidget18(),
                )
              ]),
        ),
      ),
    ));
  }
}
